### ISSUE TITLE
Tmds.DBus does not support mono

### ISSUE THREAD

**Issue by MarcusWichelmann** [tmds/Tmds.DBus#10]
Hi,

We _(my friend, who emailed you because of something else, and me)_ are trying to connect to the system bus using Ubuntu 16.10, .Net 4.6 and the latest version for your library (from NuGet).

Code:
```C#
using System;
using System.Threading.Tasks;
using Tmds.DBus;

namespace DBusTest
{
    public class Program
    {
        private static void Main(string[] args)
        {
            Task.Run(async () => {
                Console.WriteLine($"Address: {Address.System}");
                using(Connection connection = new Connection(Address.System))
                {
                    await connection.ConnectAsync();

                    //IWICDWireless wirelessInterface = connection.CreateProxy<IWICDWireless>("org.wicd.daemon", new ObjectPath("/org/wicd/daemon/wireless"));
                    //Console.WriteLine(wirelessInterface.GetNumberOfNetworks());
                }
            }).Wait();
        }
    }
}
```
But it fails with these exception(s): http://pastebin.com/AvX50D4b

Do you have any idea what might be causing this or how to debug this further..?
We tried to use this library (fork of dbus-sharp) before and at least the connection did work there: https://bitbucket.org/hindlemail/dbus-sharp

**Comment by tmds** [comment]
.net 4.6 doesn't run on Linux, are you using mono or .net core?
At the top of the stacetrace is says: ConnectionException: Unable to authenticate.
Can you try connecting to the session bus and see if that works?

**Comment by MarcusWichelmann** [comment]
Hey, you're fast! 😄 
Session Bus doesn't work, too..
We're trying it on Mono  4.6.2.7. Is there a way to choose to another core..?
So your library isn't Linux compatible..? I thought that, because you're providing an example about how to connect to the NetworkManager...

**Comment by tmds** [comment]
I haven't tried it with mono, only with .net core, which runs on Linux to: https://www.microsoft.com/net/core#linuxubuntu

**Comment by tmds** [comment]
@MarcusWichelmann I think I found where the code is failing on mono. I am fixing this on the bugfix/support-mono branch. I mailed a compiled version to Sören.

**Comment by MarcusWichelmann** [comment]
Wow, much thanks for your Investigation! 😉 We're trying it.
Habe never heard about net core before, but looks cool, too. 😉

**Comment by tmds** [comment]
This branch builds with mono 4.8 alpha: https://github.com/tmds/Tmds.DBus/tree/bugfix/support-mono
Unfortunately the result crashes.
I will close the issue because I will not look into this further.
