### ISSUE TITLE
NameOwnerChanged

### ISSUE THREAD

**Issue by idleroamer** [tmds/Tmds.DBus#101]
I am implementing a sort of ObjectManager which monitors the status of other connection.
The problem is the "**org.freedesktop.DBus.NameOwnerChanged**" never is received in the Tmds clients.

AFAIS the DBusConnection::HandleSignal consumes the signal without propagating it further to client watchers. Sadly the API DBusConnection::WatchNameOwnerChangedAsync (to add a watcher) is as well private (in the sense DBusConnection is private member of connection). 

For me the solution is trivial, I don't know why DBusConnection::HandleSignal can't propagate further but I am not sure if I am missing something.

Thanks for your time

**Comment by tmds** [comment]
Yes, the library eats this signal currently.

https://github.com/tmds/Tmds.DBus/pull/104 will fix this.

**Comment by idleroamer** [comment]
perfect, lovely support!

**Comment by MaticBabnik** [comment]
Any updates?

**Comment by tmds** [comment]
The new protocol library doesn't swallow the signal, but the original dbus library still does.

I don't think anyone is working on this currently.

**Comment by tmds** [comment]
Consider using the protocol library.
