### ISSUE TITLE
Tmds.Dbus.Tool bug on generating interface for org.Bluez

### ISSUE THREAD

**Issue by GianlucaCucco** [tmds/Tmds.DBus#102]
Hi I've found a bug on Generator.cs, when i'm tring to generate the interfaces for org.Bluez with experimental it goes on error cause there is a method with empty output type so i think the best way to fix that is just to add 

```
 if (string.IsNullOrEmpty(dbusType))
                return null;
```

on top of the method ParseType Ln 294 Generator.cs

   ```
     private SyntaxNode ParseType(string dbusType, ref int index, List<string> elementNames = null)
        {
            if (string.IsNullOrEmpty(dbusType))
                return null;
            char c;
            switch (c = dbusType[index++])
            {
```

**Comment by qmfrederik** [comment]
See also #98

**Comment by tmds** [comment]
Dup of https://github.com/tmds/Tmds.DBus/issues/102.
