### ISSUE TITLE
Signal Subscriptions are broken

### ISSUE THREAD

**Issue by 3dGrabber** [tmds/Tmds.DBus#103]
Situation:

I have multiple named services on the bus:

```
foo.service.a
foo.service.b
...
```

All those services publish a signal on a certain interface/objectpath/member:

`bar.interface /some/path someMember`

When I create a proxy and subscribe to said signal of `foo.service.a`,
the callback fires for `bar.interface /some/path someMember` of ALL services.

Unfortunately inside the callback handler there is no way of knowing which service was the sender.

**Comment by 3dGrabber** [comment]
`SignalMatchRule` does not seem to be able to filter for _ServiceName_

```
  internal class SignalMatchRule
    {
        public string Interface { get; set; }
        public string Member { get; set; }
        public ObjectPath? Path { get; set; }
        ...
```
https://github.com/tmds/Tmds.DBus/blob/master/src/Tmds.DBus/SignalMatchRule.cs#L10-L14

**Comment by tmds** [comment]
> Unfortunately inside the callback handler there is no way of knowing which service was the sender.

@3dGrabber I'm not sure this is part of the message that is delivered through the bus.

I don't expect it to be in the optional `SENDER` header field which afaik has the unique name assigned by the bus.

**Comment by 3dGrabber** [comment]
> I'm not sure this is part of the message that is delivered through the bus.

It's not.

> header field which afaik has the unique name assigned by the bus.

Correct.

It's a serious shortcoming of the current dbus-daemon implementation IMO.

When a client wants to subscribe to multiple signals (by means of multiple calls to `AddMatch`),
it has to locally dispatch the signal _again_, to find out which Match the incoming signal belongs to. The daemon obviously knows, but does not tell its subscribers.

For object paths, member and interfaces, this is pretty easy to do, just look at the corresponding header fields.
For the sender however it's difficult (for the reasons cited above).

I know two ways to get around this:

1. Build a look-up table `id => busName` by means of `GetNameOwner` and keep that table up to date by 
   listening to `NameOwnerChanged`, essentially syncing the daemons state into the process' memory.
   It's not 100% stable because the remote process might use a different connection/id to send signals (probably rare).
   
2. Use a separate connection for each signal/`AddMatch`, so you know exactly what match the signal corresponds to.

I generally use the second approach.


Obviously I'm not blaming you for those problems, (in fact **thank you** for writing this library).

However the API (`CreateProxy` IIRC) *seems* to suggest to be able to deal with dispatching on the sender, but silently fails.

**Comment by 3dGrabber** [comment]
>When a client wants to subscribe to multiple signals (by means of multiple calls to AddMatch),
it has to locally dispatch the signal again, to find out which Match the incoming signal belongs to. The daemon obviously knows, but does not tell its subscribers.

The way I see this could be fixed in the daemon:

- when a client calls `AddMatch` create a handle for that match rule and return it
- return that handle in the header of each signal that matches 

Unfortunately I am not fluent enough in C to contribute.

**Comment by tmds** [comment]
> Use a separate connection for each signal/AddMatch, so you know exactly what match the signal corresponds to.

imo this is the way to go.
