### ISSUE TITLE
Generate whole D-Bus API for NetworkManager

### ISSUE THREAD

**Issue by heroreo** [tmds/Tmds.DBus#107]
Hello, I am wondering if there is way generate whole APIs for NetworkManager.
I tried generate code using codegen on my Debian and it succeeded.
The generated D-Bus APIs are based on the current structure of my Debian which not contains all APIs listed in [here](https://developer-old.gnome.org/NetworkManager/stable/spec.html).
For example, if there is no modem plugged to my Debian, then no modem related API will be generated. 
So I am wondering is there way generate whole APIs for NetworkManager regardless of current D-Bus structure?

Thanks.

**Comment by tmds** [comment]
You can pass xml files to the `codegen` command.
You can find such xml files on your Linux system at `/usr/share/dbus-1/interfaces`.
On Fedora I need to install the `NetworkManager-libnm-devel` package to get them for NetworkManager.
Or maybe get them from the NetworkManager repo at https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/tree/main/introspection.
