### ISSUE TITLE
org.freedesktop.DBus.Error.UnknownObject ... Method "[Method Name]" with signature "" on interface "[Interface Name]" doesn't exist

### ISSUE THREAD

**Issue by adamwendel** [tmds/Tmds.DBus#110]
I am trying to implement the Dbus service for Bluez, where the c# code is in charge of being the GATT "server". According to the documentation for the org.bluez service, one has to create a tree structure like this:
```
-> /com/example
  |   - org.freedesktop.DBus.ObjectManager
  |
  -> /com/example/service0
  | |   - org.freedesktop.DBus.Properties
  | |   - org.bluez.GattService1
  | |
  | -> /com/example/service0/char0
  | |     - org.freedesktop.DBus.Properties
  | |     - org.bluez.GattCharacteristic1
```

It's my understanding that a Dbus Object of type `org.freedesktop.DBus.ObjectManager` needs to be created at path `/com/example`. I've seen lots and lots of examples using this library that access pre-existing dbus objects, but I'm lost on how to create one.
 this is what I've tried: `var genericObjectProxy = systemConnection.CreateProxy<IObjectManager>(BluezConstants.BluezService, "/com/example");`

The DbusObject Interface looks like the following:
```csharp
[DBusInterface("org.freedesktop.DBus.ObjectManager")]
public interface IObjectManager : IDBusObject
{
	Task<IDictionary<ObjectPath, IDictionary<string, IDictionary<string, object>>>> GetManagedObjectsAsync();
	Task<IDisposable> WatchInterfacesAddedAsync(Action<(ObjectPath @object, IDictionary<string, 						IDictionary<string, object>> interfaces)> handler, Action<Exception> onError = null);
	Task<IDisposable> WatchInterfacesRemovedAsync(Action<(ObjectPath @object, string[] interfaces)> handler, Action<Exception> onError = null);

}
```

when I try to call `var managedObjects = await genericObjectProxy.GetManagedObjectsAsync();` I get the following exception: 

```
An exception of type 'Tmds.DBus.DBusException' occurred in 
System.Private.CoreLib.dll but was not handled in user code: 
'org.freedesktop.DBus.Error.UnknownObject: Method "GetManagedObjects" 
with signature "" on interface "org.freedesktop.DBus.ObjectManager" doesn't exist'
```

Edit: note that the DBusInterface for `IObjectManager` is what came out of `codegen`

**Comment by tmds** [comment]
To add an object on the bus you need to call `RegisterObjectAsync`. You can find some examples in the tests.
