### ISSUE TITLE
IDictionary<string, object> GetAllAsync() fail

### ISSUE THREAD

**Issue by Ordsall** [tmds/Tmds.DBus#116]
When I create method GetAllAsync() with SomeCalss with attribute [Dictionary] as return parameter - all work.
But when I create method with GetAllAsync() with IDictionary<string, object>, object is hosted, but it's empty and no contains properties methods.
![screenshot](https://user-images.githubusercontent.com/13125056/148582646-4a526e49-176d-4283-bf58-b5e62df96cd6.png)
```
public class CameraProperties : ICameraProperties
    {
        public ObjectPath ObjectPath => new ObjectPath("/tmds/dbus/tests/propertyobject");
        public event Action<PropertyChanges> OnPropertiesChanged;

        IDictionary<string, object> properties = new Dictionary<string, object>() { { "Test", 15 } };

        public Task<IDictionary<string, object>> GetAllAsync()
        {
            return Task.FromResult(properties);
        }

        public Task SetAsync(string prop, object val)
        {
            properties[prop] = val;
            OnPropertiesChanged?.Invoke(PropertyChanges.ForProperty(prop, val));
            return Task.CompletedTask;
        }

        public Task<object> GetAsync(string prop)
        {
            return Task.FromResult(properties[prop]);
        }

        public Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler)
        {
            return SignalWatcher.AddAsync(this, nameof(OnPropertiesChanged), handler);
        }
    }
```

**Comment by tmds** [comment]
> But when I create method with GetAllAsync() with IDictionary<string, object>, object is hosted, but it's empty and no contains properties methods.

You mean the introspection information doesn't provide property information?

For that to work, you need to use the `[Dictionary]` attribute. The information is derived from the type that has the attribute.

**Comment by Ordsall** [comment]
> You mean the introspection information doesn't provide property information?

Yeap!

> For that to work, you need to use the [Dictionary] attribute.

For what? For `IDictionary<string, PropertyDescriptionContainer>`. If I use class with `[Dictionary]` attribute, all works fine. But I want use `IDictionary<string, PropertyDescriptionContainer>`, because I create properties list runtime, by receiving it from other different devices.
