### ISSUE TITLE
Running on Main Thread ?

### ISSUE THREAD

**Issue by mikkeljohnsen** [tmds/Tmds.DBus#118]
Is a Watch returning on a separate Thread ?
 
```
await device.WatchStateChangedAsync(
        change => Console.WriteLine($"{interfaceName}: {change.oldState} -> {change.newState}")
    );
```
Is there anyway to make it always use/return on Main Thread ?

Reason for question, is I get crashes on UI if not Invoking the Watch on Main Thread.

**Comment by tmds** [comment]
> Is there anyway to make it always use/return on Main Thread ?

You need to create a `Connection` and set `ConnectionOptions.SynchronizationContext` to the UI's `SynchronizationContext`.

**Comment by mikkeljohnsen** [comment]
Thank it works
