### ISSUE TITLE
Possible NullReferenceException in DBusConnection.HandleMessage(Message)

### ISSUE THREAD

**Issue by rquackenbush** [tmds/Tmds.DBus#12]
I noticed the following code:

```
if (pending != null)
{
     pending.SetResult(msg);
}
else
{
      pending.SetException(new ProtocolException("Unexpected reply message received: MessageType = '" + msg.Header.MessageType + "', ReplySerial = " + serialValue));
}
```
https://github.com/tmds/Tmds.DBus/blob/a93383419db10ddc43fa18ca2ae8d7154fda99b8/src/Tmds.DBus/DBusConnection.cs#L521

If the pending task isn't found, a NullReferenceException will be thrown. I'm not sure what the ultimate solution should be there... Just throwing the Protocol exception could present issues too by stopping the message loop.

**Comment by tmds** [comment]
good catch!
Protocol exceptions are serious enough to stop the message loop.
Do you feel like sending a PR? If not, I'll take care of it when I find some time.
