### ISSUE TITLE
dotnet-dbus tool codegen for org.bluez

### ISSUE THREAD

**Issue by alberk8** [tmds/Tmds.DBus#138]
I am using the the version 0.10.1 tool to generate the dbus service org.bluez  but it seems to be missing the `org.bluez.GattService1` and `org.bluez.GattCharacteristic1` interfaces.  Am I missing some commands in the codegen tool?

`dotnet-dbus codegen   --service org.bluez --bus system`

```
dotnet-dbus list objects --bus system --service org.bluez
/ : org.freedesktop.DBus.ObjectManager
/org/bluez : org.bluez.AgentManager1 org.bluez.ProfileManager1
/org/bluez/hci0 : org.bluez.Adapter1 org.bluez.GattManager1 org.bluez.LEAdvertisingManager1 org.bluez.Media1 org.bluez.NetworkServer1
```

OS: Ubuntu 20.04
Bluetooth: Detected Intel(R) Wireless-AC 9260 160MHz, REV=0x324 (WiFi with BLE)
Dotnet: 6.0.201

**Comment by tmds** [comment]
The code gen tool works by introspecting the objects exposed by the service. If the service doesn't expose any object with those interfaces, they won't be part of the generated code.
You can also pass interface xml files to the tool, and it will generate code for them. You can find such files in `/usr/share/dbus-1/interfaces` or as part of the project's sources.
