### ISSUE TITLE
Authentication failure after setreuid()

### ISSUE THREAD

**Issue by dh2i-sam** [tmds/Tmds.DBus#149]
I'm trying to use Tmds.DBus in an application that starts as root, and drops privileges.

Initially, I had it connect to D-Bus, drop privileges via setreuid(), disconnect from D-Bus, and reconnect as the new user.  It needs to connect as the new user in order to claim a certain D-Bus endpoint.  Unfortunately, the second connection attempt fails with an authentication error:

System.AggregateException: One or more errors occurred. (Authentication failure)
 ---> Tmds.DBus.ConnectException: Authentication failure
   at Tmds.DBus.Transports.Transport.SendAuthCommands(String userId)
   at Tmds.DBus.Transports.Transport.DoClientAuth(Guid guid, String userId)
   at Tmds.DBus.Transports.Transport.ConnectAsync(AddressEntry entry, ClientSetupResult connectionContext, CancellationToken cancellationToken)
   at Tmds.DBus.DBusConnection.ConnectAsync(ClientSetupResult connectionContext, Action`1 onDisconnect, CancellationToken cancellationToken)
   at Tmds.DBus.Connection.DoConnectAsync()
   at Tmds.DBus.Connection.ConnectAsync()
   --- End of inner exception stack trace ---

The initial UID is 0 (root), and the new (unprivileged) UID is 130.  During the second connection attempt, after dropping to UID 30, in order to authenticate, Tmds.DBus sends:

AUTH EXTERNAL 30\r\n

Which is essentially asking the D-Bus daemon to let it in as UID 0.

It would appear that the failure is due to how Tmds.DBus.Environment.UserId operates -- it samples the user ID once by calling geteuid(), and returns the same result in all subsequent get operations.  Thus, if the process user ID changes, socket authentication will fail for subsequent connection attempts.

Would it be possible to not cache the UID here?  It's not like it's a very expensive system call.

**Comment by tmds** [comment]
> Would it be possible to not cache the UID here? It's not like it's a very expensive system call.

I'm fine if this doesn't get cached. Do you want to make a PR for this change.

In the meanwhile, you could implement your own `ClientConnectionOptions` and override `SetupAsync` which gives you full control of the `UserId`.
