### ISSUE TITLE
Release Tmds.DBus.Protocol package to NuGet

### ISSUE THREAD

**Issue by loligans** [tmds/Tmds.DBus#150]
Hello, thank you for writing such a useful library for interacting with DBus in dotnet!!

Is there a reason why `Tmds.DBus` is on NuGet but `Tmds.DBus.Protocol` is not?

**Comment by tmds** [comment]
The `Protocol` library is a work in progress to support aot scenarios.

I hope to have something on nuget.org in half a year. In the meanwhile you can grab a build of this nuget feed:

```
<add key="tmds" value="https://www.myget.org/F/tmds/api/v3/index.json" />
```

I appreciate any feedback you have about the `Protocol` library.

**Comment by leemichmsft** [comment]
Hi, I was wondering if you had any updates on this? I want to use the library but need to use it in an aot scenario, the Protocol library has been doing the trick for me andI was wondering if you still plan on releasing it to nuget.org sometime

**Comment by tmds** [comment]
The protocol library is now on nuget.org.
