### ISSUE TITLE
Asynchronous DBus Protocols

### ISSUE THREAD

**Issue by loligans** [tmds/Tmds.DBus#151]
Hello, I have been using the Tmds.DBus.Protocols package and wondered if it would be possible to make the `TryHandleMethod` asynchronous?

**Comment by tmds** [comment]
Yes, this is could be meaningful.

If you make a PR that changes the method to return a `ValueTask<bool>`, I'll accept it.

My current focus for the `Protocol` lib is on consuming objects. After that, I want to look further at providing objects, and improve the `IMethodHandler`.

**Comment by tmds** [comment]
> If you make a PR that changes the method to return a ValueTask<bool>, I'll accept it.

I just realize this is a challenge because `ref struct` and async don't mix well.

I will definitely look into this when I revisit the _providing objects_.
