### ISSUE TITLE
Generate Private Fields as _camelCase

### ISSUE THREAD

**Issue by DamianSuess** [tmds/Tmds.DBus#170]
Let me first say, THANK YOU!! Love this NuGet package for our Linux-based projects!

As a feature request, could we have the generator output the property's private fields as `_camelCase` rather than in `_PascalCase` format?  This would greatly reduce the warnings we get in our codebase from the generated file.  If this is a design decision, could we at least include a command line switch?

For what it's worth, this pattern matches most standard C# practices, and the [dotnet runtime coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md). 

Thank you,
Damian

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/Tmds.DBus/pull/171.
