### ISSUE TITLE
Any way to register a service?

### ISSUE THREAD

**Issue by 17steen** [tmds/Tmds.DBus#172]
Hello, I'm trying to register a service on the session Bus.

Using `DBus.Protocol` there doesn't seem to be a way to give my Implementation a service name.
And using the`DBus.Connection.Session!.Register*Async` methods throw exceptions.

Is this still WIP?

**Comment by tmds** [comment]
DBus.Protocol is very much a work in progress.

If you use the regular DBus library, registering services should work.
