### ISSUE TITLE
'Tmds.DBus.DisconnectedException' in application connecting to BlueZ on Raspberry Pi 0 W 2

### ISSUE THREAD

**Issue by maciej-napora** [tmds/Tmds.DBus#173]
Hello,

I am developing a .NET 6 application and I am running it on Raspberry OS Bullseye. I am using BlueZ 5.55 and Tmds.DBus. After some time of operation I see a number of exceptions thrown in the VS debugger attached to the application:

_Exception thrown: 'Tmds.DBus.DisconnectedException' in System.Private.CoreLib.dll_

The applications stops performing its functionality, which is periodically to start discovery, retrieve devices and connect over Bluetooth Low Energy to them. Judging by the symptoms, I suspect that the application is losing a connection to DBus. I was looking through the source code of Tmds.DBus and I found that the connection to the system bus (which I use) is created with `AutoConnect =true`:
`var newConnection = new Connection(new ClientConnectionOptions(address) { AutoConnect = true, SynchronizationContext = null });`

Is there a reconnection to DBus done automatically when AutoConnect is set to true? Is there anything I can do to re-establish connection? After I restart the application it works for some time and the exception are thrown again.

Any help appreciated.

**Comment by tmds** [comment]
AutoConnect will cause a connection to be re-established for a method call.
For signals, the `onError` handler will be called. Then you need to manually subscribe again.
