### ISSUE TITLE
Errors when referencing Tmds.DBus.Tool

### ISSUE THREAD

**Issue by hansmbakker** [tmds/Tmds.DBus#176]
When referencing `Tmds.DBus.Tool` in a `net6.0` or `net7.0` project, I get these errors in some cases:
```
error NU1202:
Package Tmds.DBus.Tool 0.11.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Tmds.DBus.Tool 0.11.0 supports: 
- net6.0 (.NETCoreApp,Version=v6.0) / any
- netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any 
Invalid project-package combination for Tmds.DBus.Tool 0.11.0. DotnetToolReference project style can only contain references of the DotnetTool type
```

I got them in Visual Studio sometimes / sometimes not and thought it was a build system glitch, but now I get them when building my project using `dotnet build` on the command line in WSL.

Is this a known issue, and is there a solution for this?

**Comment by hansmbakker** [comment]
I suspect this is because in WSL I have the dotnet 7.0 SDK installed while on Windows I have both 6.0 and 7.0 installed.

Can I add a PR to make the tool compatible with dotnet 7.0?

**Comment by tmds** [comment]
> netcoreapp2.2

Did your system only have .NET 2.2 when you tried to installed the tool?
