### ISSUE TITLE
Dictionary fields not deserialising

### ISSUE THREAD

**Issue by archanox** [tmds/Tmds.DBus#178]
When obtaining the gelocation from `org.freedesktop.GeoClue2` the location `GetAll()` call does not populate the fields for the `LocationProperties` Dictionary.

I double checked with [Bustle](https://flathub.org/apps/details/org.freedesktop.Bustle) to see if the data is being returned, and it is.

I pulled down the Tmds.DBus project and referenced it within my project and stepped through the code.
The problematic method is `ReadDictionaryObject<T>()` within MessageReader.cs

The field names in `fis` are formatted as `<Latitude>k__BackingField` which the following lambda does not capture.
```csharp
var field = fis.Where(f =>   ((f.Name.Length == key.Length) || (f.Name.Length == key.Length + 1 && f.Name[0] == '_'))
                                          && (f.Name.EndsWith(key, StringComparison.Ordinal) || (key.Contains("-") && f.Name.Replace('_', '-').EndsWith(key, StringComparison.Ordinal)))).SingleOrDefault();
```

To remedy my issue I just included right after this check the following
```csharp
if (field == null)
{
    field = fis.SingleOrDefault(x => x.Name.StartsWith('<' + key + '>'));
}
```
and everything appears to work again.

I'd submit a proper fix as a PR, but it feels like the issue is caused elsewhere. Although there is code in the if block below it that appears unfinished.

```csharp
if (field == null)
{
    var value = Read(sig.ToType());
}
```

**Comment by tmds** [comment]
> The field names in fis are formatted as <Latitude>k__BackingField which the following lambda does not capture.

Yes, the code doesn't support auto-generated backing fields. I'd welcome a PR to add it.

> Although there is code in the if block below it that appears unfinished.

This skips the value in case no matching field is found. It is good as is.
