### ISSUE TITLE
Determine active connection to get DHCP setting from NetworkManager

### ISSUE THREAD

**Issue by HakanL** [tmds/Tmds.DBus#181]
Ultimately I'm looking to use Tmsd.DBus to get the network settings on a Linux (Raspberry Pi) box running .NET7. I can successfully get the IP address, gateway and a few other settings, but I can't figure out how to get the DHCP setting (ipv4.method), it doesn't seem to exist anywhere, but I also just know enough about DBus/NM to be dangerous. I've provided this little console app as a WIP to get the DHCP settings, but I'm stuck on getting the active connections (to see if there is a property for method in there). Please help.

https://github.com/HakanL/CSharpDbusNetworkManager

**Comment by WillooWisp** [comment]
I do this, by geting the connectionSettings dictionary from the connection, IConnection.GetSettingsAsync. Then get the value for "connection". Create a dictionary for the ipv4 settings, var ipv4Settings = new Dictionary<string, object>(), and set the ipv4Settings["method"] = "auto". Then assign this ipv4 settings dictionary to the connection settings dictionary retrieved earlier, connectionSettings["ipv4"] = ipv4Settings and call connection.UpdateAsync(connectionSettings).
