### ISSUE TITLE
docs/protocol.md example does not compile

### ISSUE THREAD

**Issue by madewokherd** [tmds/Tmds.DBus#185]
I ran into the following issues:
 * `AddImplementation.RunMethodHandlerSynchronously` needs to be public to implement the interface method.
 * `AddImplementation.HandleMethodAsync references undefined `message` and `connection` variables, it seems they should have been `request` and `context` respectively.
 * `AddImplementation.HandleMethodAsync references undefined `connection` variable, it seems it should have been `context`.

I can write a PR for this if you prefer. At the moment, I am testing a .NET Framework build, so I had to make other changes to account for missing C# features. The example program does seem to work correctly once it builds.

**Comment by tmds** [comment]
@madewokherd I'd gladly take a PR that fixes the documentation.

**Comment by tmds** [comment]
Have you seen [affederaffe/Tmds.DBus.SourceGenerator](https://github.com/affederaffe/Tmds.DBus.SourceGenerator)? It may be of interest to you.
