### ISSUE TITLE
Generated class "NetworkManagerProperties" in NetworkManager.DBus.cs holds only empty values

### ISSUE THREAD

**Issue by Echoseven2020** [tmds/Tmds.DBus#190]
Version 0.14.1:

According to the example to invoke the `codegen` to generate a NetworkManager.DBus.cs file and then to access the properties by using the INetworkManager interface.

But the following query returns only empty properties:
`
var prop = await networkManager.GetAllAsync();
`

That is caused by the following code in file Tmds.DBus/Protocol/MessageReader.cs
`
line 382:   FieldInfo[] fis = type.GetFields (BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
`

Because the names of the generated private fields in NetworkManagerProperties use camelCasing instead of PascalCasing, which is compared with the "Key" (PascalCasing) as case-sensitive, event it filters out the leading "_".

Is this isssue already reported? 
Thank you.

**Comment by tmds** [comment]
@Echoseven2020 I assume the problem may be caused by: https://github.com/tmds/Tmds.DBus/pull/171?
If you use an older version of the tool (like `0.11.0`) probably it will work?

We need to update the `MessageReader` to account for the that change, or revert it.

**Comment by Echoseven2020** [comment]
@tmds yes, I think so.
I just adjusted the Fields of generated NetworkManager manually, and it works. 
It should work if in `MessageReader `at line 382, to use `type.GetProperty` instead of `GetFields`.
Thanks.

**Comment by tmds** [comment]
This is fixed in 0.15.0 which is now on nuget.org.

**Comment by DamianSuess** [comment]
Interesting, findings. I was surprised because this didn't affect my other projects that are using `_camelCase`. On the next branch of the [Linux.Bluetooth](https://github.com/SuessLabs/Linux.Bluetooth) project, I'm interested to see the outcomes.

To reduce code warnings and maintain common styles, I'd be interested to entertain #203's comment.
> note: we could override the key using the PropertyAttribute, but I don't think it's worth adding this attribute to each field for the sake of having camel-cased field names.
