### ISSUE TITLE
Tmds.DBus.Protocol.Connection.AddMatchAsync(emitOnCapturedContext) does not work

### ISSUE THREAD

**Issue by madewokherd** [tmds/Tmds.DBus#191]
When using AddMatchAsync with emitOnCapturedContext equal to its default value of true, calling SynchronizationContext.Current from the handler returns null.

This appears to be because, while the SynchronizationContext is saved in the observer, and there is clearly code in EmitOnSynchronizationContext to use it, EmitOnSynchronizationContext is never called and Emit is used instead.

**Comment by tmds** [comment]
> EmitOnSynchronizationContext is never called and Emit is used instead.

@madewokherd is this the fix we need, or does it need further investigation? Do you want to make a PR?

**Comment by madewokherd** [comment]
For right now, it's a guess, I haven't verified that it's enough to fix the issue.
