### ISSUE TITLE
Prepare Tmds.DBus.Protocol library for trimming

### ISSUE THREAD

**Issue by tibel** [tmds/Tmds.DBus#202]
Currently Tmds.DBus.Protocol is not marked as trimmable.

see https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming.

**Comment by WillooWisp** [comment]
I second that, would be nice if this library was compatible with trimming, in order to get a small package size when building native aot apps utilizing dbus.

**Comment by tmds** [comment]
I've created a few issues that relate to this:
- https://github.com/tmds/Tmds.DBus/issues/237
- https://github.com/tmds/Tmds.DBus/issues/228

**Comment by tmds** [comment]
The 0.17.0 version of the Protocol library includes annotations for trimming/NativeAOT and introduces new APIs for working with variants in trimmed/NativeAOT applications.

For documentation, see https://github.com/tmds/Tmds.DBus/blob/main/docs/protocol.md#nativeaottrimming.
