### ISSUE TITLE
Tmds.Dbus.Tool does not work with net6.0 (or net7.0)

### ISSUE THREAD

**Issue by dfch** [tmds/Tmds.DBus#208]
When creating a solution and adding the `Tmds.Dbus.Tool` nuget package I get the following error:

```
PS C:\src\dbus-pi\dbus-pi> dotnet restore
  Determining projects to restore...
C:\src\dbus-pi\dbus-pi\dbus-pi.csproj : error NU1202: Package Tmds.DBus.Tool 0.15.0 is not compatible with netc
oreapp2.2 (.NETCoreApp,Version=v2.2). Package Tmds.DBus.Tool 0.15.0 supports: net6.0 (.NETCoreApp,Version=v6.0)
 / any
C:\src\dbus-pi\dbus-pi\dbus-pi.csproj : error NU1212: Invalid project-package combination for Tmds.DBus.Tool 0.
15.0. DotnetToolReference project style can only contain references of the DotnetTool type
  Failed to restore C:\src\dbus-pi\dbus-pi\dbus-pi.csproj (in 223 ms).
  1 of 2 projects are up-to-date for restore.
PS C:\src\dbus-pi\dbus-pi>
```

I followed the presentation in https://youtu.be/fPsyxV8_kRg.

It seems to me that the `DotNetCliToolReference` is deprecated. When using `DotnetToolReference` there is no error, however then the `dotnet dbus` command is not available.

Any idea how to fix this? Or as an alternative? Is there an example for the files generated by the `codegen` command so I can insert them manually?
Thanks in advance for any help and hints.

**Comment by exendahal** [comment]
I my case, TMds.Dbus is working well on net6.0. In case of net7.0, I get the following error:
`System.ArgumentException: Duplicate type name with in an assembly. at System.Reflection.Emit.ModuleBuilder.CheckNameConflict(String, Type)  at Syestem.Reflection.Emit.TypeBuilder..ctor(String, TypeAttributes, Type, Type[], ModuleBuilder, PackageSize, Int32, TypeBuilder) at System.Reflection.Emit.ModuleBuilder.DefineType(String, TypeAttributes, Type, Type[] ) at Tmds.Dbus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type) at Tmds.Dbus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type) at Tmds.DBus.Connection.CreateProxy(Type, String, ObjectPath) at Tmds.DBus.Connection.CreateProxy[T](String,ObjectPath)`

Let me know, if there are some workarounds available. 
Thanks in advance for any help.

**Comment by exendahal** [comment]
I am using the .NET BLE Server with the latest updated version of Tmds.Dbus.
https://github.com/phylomeno/dotnet-ble-server

**Comment by exendahal** [comment]
@dfch  I have a small update on this.
I am getting the exception when I run my project only on the debug build.

**Comment by tmds** [comment]
The tool is published for net6.0, and should work when installed using 'dotnet tool install'.
