### ISSUE TITLE
Advice on using property classes

### ISSUE THREAD

**Issue by ilya-zlobintsev** [tmds/Tmds.DBus#209]
I'm trying to implement an interface using this library, but I'm having some difficulties with implementing property methods, and deciding if properties should be stored in a class or in a dictionary.

The modeling documentation as well the generated code suggest using classes with the `Dictionary` attribute:
```csharp
    [Dictionary]
    class MediaPlayer2Properties
    {
        public bool CanQuit = false;
        public bool CanRaise = false;
        public bool HasTrackList = false;
        public string Identity = "";
        public string[] SupportedUriSchemes = Array.Empty<string>();
        public string[] SupportedMimeTypes = Array.Empty<string>();
    }
```
When implementing the interface, this works fine for GetAllAsync:
```csharp
class MyMediaPlayer : IMediaPlayer2
{
    readonly static MediaPlayer2Properties Properties = new();

    public Task<MediaPlayer2Properties> GetAllAsync()
    {
        return Task.FromResult(Properties);
    }
```
However, the `GetAsync` and `SetAsync` methods access the properties by their names as a string. This can be worked around using reflection, though I'm not sure if it's the proper way to do it:
```csharp
    public Task<object?> GetAsync(string prop)
    {
        var value = Properties.GetType().GetField(prop)?.GetValue(Properties);
        return Task.FromResult(value);
    }

```
The generated extension methods seem to be designed for storing the properties in a dictionary, and not a class (otherwise you wouldn't need them)
```csharp
    static class MediaPlayer2Extensions
    {
        public static Task<bool> GetCanQuitAsync(this IMediaPlayer2 o) => o.GetAsync<bool>("CanQuit");
        ... etc
```
But if I'm storing them as a dictionary, what's the point of having a class?

The [PropertyObject test](https://github.com/tmds/Tmds.DBus/blob/a62998f9bf8de28a76747b6d1fe773ff013f657a/test/Tmds.DBus.Tests/PropertyObject.cs) uses a dictionary. I could not find any other examples, as most people seem to use this library for clients, and not servers.

What is the proper/recommended way to implement this?

**Comment by tmds** [comment]
> What is the proper/recommended way to implement this?

You need to implement the GetAsync/SetAsync method and map the property string argument name to the property value. You need to get the values from where you store them. For example a switch expression that returns the property values. Or if you don't want to manually write that expression, you can use reflection.
