### ISSUE TITLE
org.freedesktop.timesync1 => GetAllAsnyc throws ex 'Read pos 688 != ep 664'

### ISSUE THREAD

**Issue by Umdrahschua** [tmds/Tmds.DBus#215]
If I run following

```
[timesync1.xml.txt](https://github.com/tmds/Tmds.DBus/files/13658299/timesync1.xml.txt)
[timesync1.DBus.cs.txt](https://github.com/tmds/Tmds.DBus/files/13658298/timesync1.DBus.cs.txt)

public class UnitTest1
{
    [Fact]
    public async void DBusTest1()
    {
        var systemConnection = Tmds.DBus.Connection.System;
        var timesyncManager = systemConnection.CreateProxy<timesync1.DBus.IManager>("org.freedesktop.timesync1", "/org/freedesktop/timesync1");

        var all = await timesyncManager.GetAllAsync();
        Assert.True(all != null);
    }
}
```

Then I run into an exception "Read pos 688 != ep 664" (Read position 688 != end position 664)
 https://github.com/tmds/Tmds.DBus/blob/a62998f9bf8de28a76747b6d1fe773ff013f657a/src/Tmds.DBus/Protocol/MessageReader.cs#L459

Generated code and DBus-interface is in the attachment.

I can debug this, but I do not know for what I should look and how this is working (https://github.com/tmds/Tmds.DBus/blob/a62998f9bf8de28a76747b6d1fe773ff013f657a/src/Tmds.DBus/Protocol/MessageReader.cs#L379C21-L379C21)

Why do I not get a read error, because it is reading over the end position, if understand the message correct.

[timesync1.xml.txt](https://github.com/tmds/Tmds.DBus/files/13658315/timesync1.xml.txt)
[timesync1.DBus.cs.txt](https://github.com/tmds/Tmds.DBus/files/13658316/timesync1.DBus.cs.txt)

**Comment by Umdrahschua** [comment]
For property NTPMessage `(uuuuittayttttbtt)` I get following type

```c#
{System.ValueTuple`8[
    System.UInt32,
    System.UInt32,
    System.UInt32,
    System.UInt32,
    System.Int32,
    System.UInt64,
    System.UInt64,
    System.ValueTuple`8[
        System.Byte[],
        System.UInt64,
        System.UInt64,
        System.UInt64,
        System.UInt64,
        System.Boolean,
        System.UInt64,
        System.ValueTuple`1[
            System.UInt64
        ]
    ]
] _NTPMessage}
``` 

Could it be that the (nested) tuples are a problem?

**Comment by tmds** [comment]
> If I interpret this correct, then the reply is 664 bytes long but this looks to be too short.

You are reading it correctly.

I hope you get wiser while debugging this further.

Otherwise, I'll see if I can reproduce the issue on my machine.

**Comment by Umdrahschua** [comment]
Meanwhile I think I do not read it correctly. The first line (16 bytes) in the hex viewer is something Byte-Array internal stuff.

Data starts at line 0x10 with the length of 648 bytes. And that looks to be correct.

**Comment by tmds** [comment]
The data the message reader has is 644 bytes long, the end position of the dictionary is calculated at 664 bytes (from your first comment: `ep 664`). That's the end of the array.

Assuming the `memory.bin` at the right is showing that array, the dictionary content seems to go past the the array.

I might expect such an exception to occur sooner, when the reader goes past the array boundary while looping in:

https://github.com/tmds/Tmds.DBus/blob/a62998f9bf8de28a76747b6d1fe773ff013f657a/src/Tmds.DBus/Protocol/MessageReader.cs#L451-L456

I hope this helps your debugging efforts.

**Comment by Umdrahschua** [comment]
So I came to the issue closer. If I fix `_pos` manually then I get all properties with correct values.

After processing the second last property "NTPMessage -> (uuuuittayttttbtt)", `_pos` is incorrect. The values are all correct. But then something goes wrong during parsing the field of type

```
{ System.ValueTuple`8
    [ System.UInt32,
      System.UInt32,
      System.UInt32,
      System.UInt32,
      System.Int32,
      System.UInt64,
      System.UInt64,
      System.ValueTuple`8
      [ System.Byte[],
        System.UInt64,
        System.UInt64,
        System.UInt64,
        System.UInt64,
        System.Boolean,
        System.UInt64,
        System.ValueTuple`1
        [ System.UInt64 ]
      ]
    ] 
_NTPMessage}
```

**Comment by tmds** [comment]
Happy you figured it out!

A struct with one member...

@Umdrahschua can you make a pull request to fix the issue?

**Comment by Umdrahschua** [comment]
Yes, I can open a PR.

> A struct with one member...

No, it is not a structure with one member. I try to explain it.

I'd like to get all properties, an array of dict(string, variant), from DBus interface `org.freedesktop.timesync1.Manager`.

The property type of NTPMessage is defined as `type="(uuuuittayttttbtt)"`.

The code generator create following C# type `public (uint, uint, uint, uint, int, ulong, ulong, byte[], ulong, ulong, ulong, ulong, bool, ulong, ulong) NTPMessage`. A tuple with a lot of items.

But there can only be 8 items in a tuple. During debugging, I see a tuple with nested tuples: `( uint, uint, uint, uint, int, ulong, ulong, nested tuple 1 ( byte[], ulong, ulong, ulong, ulong, bool, ulong, nested tuple 2 ( ulong ) ) )`. 

And `nested tuple 2` triggers the issue.


This only happens if I try to get all properties. Getting only property NTPMessage is working fine.

**Comment by tmds** [comment]
Ah, I see. The 1 element tuple is of the ValueTuple overflowing into additional ValueTypes.

Support for such types was added in https://github.com/tmds/Tmds.DBus/pull/18.

**Comment by Umdrahschua** [comment]
@tmds 

I have one question. I debugged the code a little bit to found a way to reproduce the issue a test and found something that looks to be not correct

```
object MarshalStruct (Type structType, FieldInfo[] fis)
{
    object strct = Activator.CreateInstance (structType);
    int sof = Marshal.SizeOf (fis[0].FieldType);
    GCHandle handle = GCHandle.Alloc (strct, GCHandleType.Pinned);
    DirectCopy (sof, (uint)(fis.Length * sof), handle); // 1 * 8
    handle.Free ();

    return strct;
}

void DirectCopy (int sof, uint length, GCHandle handle)
{
    DirectCopy (sof, length, handle.AddrOfPinnedObject ());
}

unsafe void DirectCopy (int sof, uint length, IntPtr handle)
{
    if (_endianness == Environment.NativeEndianness) {
        Marshal.Copy (_data.Array, _data.Offset + _pos, handle, (int)length);
    } else {
        byte* ptr = (byte*)(void*)handle;
        for (int i = _pos; i < _pos + length; i += sof)
            for (int j = i; j < i + sof; j++)
                ptr[2 * i - _pos + (sof - 1) - j] = _data.Array[_data.Offset + j];
    }

    _pos += (int)length * sof; // (1 * 8) * 8
}
```

_pos is incremented by `fis.Length * sof * sof`??? - This looks to be wrong

**Comment by tmds** [comment]
> _pos is incremented by fis.Length * sof * sof??? - This looks to be wrong

Yes, that's wrong. We no longer need to multiply by `sof`.

**Comment by Umdrahschua** [comment]
And that is trigger of the bug. Now I can reproduce this issue in the test.

**Comment by Umdrahschua** [comment]
I closed the issue because the problem was found and PR is open
