### ISSUE TITLE
Adding default DBus interfaces on all objects

### ISSUE THREAD

**Issue by jmacato** [tmds/Tmds.DBus#220]
DBus objects handled by this library should have Introspection, Peer and Properties interfaces so they are standards compliant, can be debugged by apps like D-Feet and features like SNI TrayIcons will work on weird distros like Deepin etc. 

See https://github.com/tmds/Tmds.DBus/pull/213#issuecomment-1895560082 for prior discussions.

**Comment by tmds** [comment]
The `Tmds.DBus` library handles all of these.

For `Tmds.DBus.Protocol` library the responsabilities are split between the library and the `IMethodHandler` implementation.

- The library must handle `Peer`. This is missing.

- For properties, presumably the `IMethodHandler` is already capable of handling these.

- `Introspection` for parent paths that have no `IMethodHandler` should be handled by the library. This is missing.
For paths that have an `IMethodHandler`, it is the responsability of the handler. To include child node names, the `IMethodHandler` should be able to query the direct child names that are known on the `Connection`. This API is missing.

**Comment by tmds** [comment]
> The library must handle Peer. This is missing.

This is fixed by https://github.com/tmds/Tmds.DBus/pull/221.

**Comment by tmds** [comment]
This is implemented.

@jmacato this should resolve the issue you mentioned and debugged in https://github.com/tmds/Tmds.DBus/pull/213#issuecomment-1895269667.
