### ISSUE TITLE
Protocol: add methods for removing MethodHandlers

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.DBus#225]
There are no public methods for removing MethodHandlers. This issue tracks adding those.

It may be desired to be able to remove an entire subtree (with or without the subtree root).
Also from an implementation perspective that would be more efficient than removing all handlers one by one.

This issue is open for indicating interest for the feature and sharing requirements.

**Comment by jmacato** [comment]
Hi @tmds 

We have the ff PR on avalonia that touches this issue:

https://github.com/AvaloniaUI/Avalonia/pull/15582

Hopefully we could add a way to dispose a method handler properly or at least have this method public

**Comment by jmacato** [comment]
@tmds yes that API is sufficient for our needs, thanks!

**Comment by tmds** [comment]
@jmacato I've added these members. I'll make a release at the end of the week.

**Comment by tmds** [comment]
This is part of 0.18.0 which was just uploaded to nuget.org.
