### ISSUE TITLE
Protocol: experiment with different type handling for NativeAOT support.

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.DBus#237]
Currently, a user can do something like:
```cs
writer.WriteStruct(5, new Dictionary<string, long>());
```
for which the compiler calls `WriteStruct<T1, T2>` with `<T1, T2> = <int, Dictionary<string, long>>`.

We can't unpack `T2` to get the `TKey` and `TValue` from the `Dictionary`.

and therefore require the user to call the following static method to ensure the type is writable.
```cs
MessageWriter.AddDictionaryTypeWriter<string, long>();
```

(Similar methods exist for registering type readers.)

It's not intuitive a user should do this. This issue is for exploring a different approach.

For composite types, we introduce a `struct` which implements an interface that does the serialization/deserialization.

```cs
struct Array<T> : IDBusSerializable { ... }
struct Dict<TKey. TValue> : IDBusSerializable { ... }
struct Struct<T1, T2> : IDBusSerializable { ... }
struct Struct<T1, T2, T3> : IDBusSerializable { ... }
...
struct Variant : IDBusSerializable { ... }
```

The previous call will then be:
```cs
writer.Write<Struct<string, Dict<int, long>>>(...);
```
This is simpler to understand as we can make a finite list of types that can be used for reading and writing, and the user no longer needs to call methods to add type writers/readers.

In most cases, a source-generator should be able to hide these composite type structs by using them only in the generated member implementations and using BCL types on the public API.

**Comment by softlion** [comment]
So let's start the source generator ?

**Comment by tmds** [comment]
> So let's start the source generator ?

There is a source generator here: https://github.com/affederaffe/Tmds.DBus.SourceGenerator.

> Gihub discussions are not enabled ? Nor project tasks ?

No, there isn't much need for it, everything is handled through issues.
