### ISSUE TITLE
Codegen: System.ArgumentNullException: Value cannot be null. (Parameter 'address')

### ISSUE THREAD

**Issue by uriel-kluk** [tmds/Tmds.DBus#274]
Hello,

I am running the command you provided in the documentation:
`dotnet dbus codegen --bus system --service org.freedesktop.NetworkManager --interface org.freedesktop.NetworkManager.Connection.Active:ActiveConnection`

But I it is returning the following error:
```text
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'address'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'address')
   at Tmds.DBus.ClientConnectionOptions..ctor(String address) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus/ClientConnectionOptions.cs:line 25
   at Tmds.DBus.Tool.CodeGenCommand.GenerateCodeAsync(CodeGenArguments codeGenArguments) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 179
```

Do I need to run the codegen from a Linux machine with `networkmanager`, or can I invoke it from my Windows development box?

Thanks,
Uri Kluk

**Comment by tmds** [comment]
> Do I need to run the codegen from a Linux machine with networkmanager

Yes. Alternatively, you can get the xml files (like from https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/tree/main/introspection) and pass the file names to the `codegen` command.
