### ISSUE TITLE
Deadlock on disposing signal subscriptions

### ISSUE THREAD

**Issue by M0ns1gn0r** [tmds/Tmds.DBus#279]
Hi, we're using the following interface:

```cs
[DBusInterface("de.pengutronix.rauc.Installer")]
interface IRauc : IDBusObject
{
    Task InstallAsync(string Source);
    Task<(string compatible, string version)> InfoAsync(string Bundle);
    Task<(string slotName, string message)> MarkAsync(string State, string SlotIdentifier);
    Task<(string, IDictionary<string, object>)[]> GetSlotStatusAsync();
    Task<string> GetPrimaryAsync();
    Task<IDisposable> WatchCompletedAsync(Action<int> handler, Action<Exception> onError = null);
    Task<T> GetAsync<T>(string prop);
    Task<RaucProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
}
```

Here is how we use that `IRauc raucClient`:
```cs
public async Task InstallUpdate(string raucbPath)
{
    var installCompletion = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);

    using var completionWatch = await raucClient.WatchCompletedAsync(
        r => installCompletion.TrySetResult(r),
        ex => installCompletion.TrySetException(ex));

    using var progressWatch = await raucClient.WatchPropertiesAsync(changes => ...logging and processing it...);

    await raucClient.InstallAsync(raucbPath);

    var returnCode = await installCompletion.Task;
    if (returnCode != 0)
    {
        throw new RaucUpdateFailedException($"InstallAsync failed, return code: {returnCode}.");
    }
}
```

By the nature of `using` operator, `completionWatch` and `progressWatch` are getting disposed at the end of `InstallUpdate` method. One in ~10 calls to `InstallUpdate` ends up in a deadlock :(

![image](https://github.com/tmds/Tmds.DBus/assets/5908454/332f7867-100f-4e2d-b13c-279832c5d88d)

We would be very grateful if you could investigate and fix this.

**Comment by tmds** [comment]
@M0ns1gn0r I've pushed a fix to the main branch.

Could you try using the CI packages https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#ci-packages and see if the issue no longer occurs after some reasonable amount of attempts?

**Comment by M0ns1gn0r** [comment]
@tmds Thanks! I have tested the package with a custom build on a VM and everything looks fine. The only problem is that sometimes we don't see the original problem for a week and then suddenly we have 3 occurrences on the same day. Unfortunately,  I cannot put an experimental package in our main build to give it a longer, proper test.

But I guess the fix didn't break anything big, at least. Will you publish a release?

**Comment by tmds** [comment]
I plan to make a release by the end of the week.

**Comment by tmds** [comment]
This is part of 0.18.0 which was just uploaded to nuget.org.
