### ISSUE TITLE
Expected signature 's' does not match actual signature '' in MediaPlayerRemote sample

### ISSUE THREAD

**Issue by DomiStyle** [tmds/Tmds.DBus#292]
I have been playing around with getting the MPRIS state of media players with `Tmds.DBus.Protocol`, which has been working fairly well.

However, there is one player which I can't read which is Finamp from Flathub (https://flathub.org/apps/com.unicornsonlsd.finamp).

When the PlaybackStatus is read from that player via `GetPlaybackStatusAsync()` I get the following exception:

```
Exception has occurred: CLR/Tmds.DBus.Protocol.ProtocolException
An exception of type 'Tmds.DBus.Protocol.ProtocolException' occurred in Tmds.DBus.Protocol.dll but was not handled in user code: 'Expected signature 's' does not match actual signature ''
   at Tmds.DBus.Protocol.ThrowHelper.ThrowUnexpectedSignature(ReadOnlySpan`1 signature, String expected)
   at Tmds.DBus.Protocol.Reader.ReadSignature(String expected)
   at DomiStreamDeck.Dbus.MprisObject.ReadMessage_v_s(Message message, MprisObject _) in Mpris.cs:line 1423
   at DomiStreamDeck.Dbus.Player.<>c.<GetPlaybackStatusAsync>b__27_0(Message m, Object s) in Mpris.cs:line 452
   at Tmds.DBus.Protocol.DBusConnection.<>c__45`1.<CallMethodAsync>b__45_0(Exception exception, Message message, Object state1, Object state2, Object state3)
```

Same thing happens with `ReadMetadataAsync()` but in `ReadMessage_v_aesv()`.

`Mpris.cs` is the `MPris.DBus.cs` from the `MediaPlayerRemote` sample. The exception occurs in the following line: https://github.com/tmds/Tmds.DBus/blob/main/samples/MediaPlayerRemote/Mpris.DBus.cs#L1423
The exception also happens when using the sample directly.

KDE has no issue displaying the currently playing media and controlling Finamp.

In case any testing needs to be done, Jellyfin provides a test server to use at `https://demo.jellyfin.org/stable` with login `demo` and no password.

**Comment by tmds** [comment]
> I have been playing around with getting the MPRIS state of media players with Tmds.DBus.Protocol, which has been working fairly well.

Great, happy to hear that!

> When the PlaybackStatus is read from that player via GetPlaybackStatusAsync() I get the following exception:

The MPRIS spec defines `PlaybackStatus` as a string (`"s"`), and the library is trying to read it as a string.

The exception message says: _Expected signature 's' does not match actual signature ''_.
So we learn the actual signature is empty.

You can add some code to account for the behavior of Finamp.

It could be something like:
```cs
var reader = message.GetBodyReader();
Utf8Span sig = reader.ReadSignature();
return sig.Span == "s"u8 ? reader.ReadString() : "";
```

**Comment by DomiStyle** [comment]
I tried the code snippet but I assume it's expected that it returns nothing now if no string signature is received?

I took a closer look at things in DBusViewer and it seems like this is a fault in Finamp's MPRIS implementation?

VLC returns a QString while Finamp just returns it without a variant:
![image](https://github.com/tmds/Tmds.DBus/assets/975131/9624f794-e628-4b4c-ae72-ea7e8bd2480e)
(top is Finamp, bottom is VLC)

I'm just surprised that KDE has no issue detecting the playing media even though the signature doesn't match. Do they use a different method to get metadata or do they fallback to read as string anyway if no signature is available?

Requesting `GetAll` for `org.mpris.MediaPlayer2.Player` on `org.freedesktop.DBus.Properties` seems to work, the correct data types are returned there.

I was able to get the `WatchPropertiesChangedAsync` function to work by ignoring `HasChanged` and `IsInvalidated` and first checking if `changes.Properties.PlaybackStatus` is not null. I do get valid metadata there, of course that doesn't help me getting the initial state.

**Comment by tmds** [comment]
> I tried the code snippet but I assume it's expected that it returns nothing now if no string signature is received?

Yes, it returns an empty string. You can change it further to account for Finamp's exact behavior.

> it seems like this is a fault in Finamp's MPRIS implementation?

Yes.

`PlaybackStatus` is a string property: https://gitlab.freedesktop.org/mpris/mpris-spec/-/blob/master/spec/org.mpris.MediaPlayer2.Player.xml?ref_type=heads#L312.

When you get a property through org.freedesktop.DBus.Properties it should be wrapped in a variant: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties.

> Requesting GetAll for org.mpris.MediaPlayer2.Player on org.freedesktop.DBus.Properties seems to work, the correct data types are returned there.

This may be what KDE is using, you can check with some D-Bus monitor tool.

**Comment by DomiStyle** [comment]
I dug a little deeper and `reader.ReadSignature` actually returns `???Play` or `00 00 00 50 6C 61 79`. Which seems to be "Playing" but with the "ing" cut off because of the 3 0 bytes.

Which is an issue because if I call `reader.ReadSignature` before `reader.ReadString` I will  go outside of the array bounds.

On the other hand, `GetPropertiesAsync` works if I comment out `Position` because it returns type v instead of x.

I could not find out how KDE gets the initial state since there's not a single MPRIS call being logged but I can see that it requests the position after each `PropertiesChanged` event.

I did check the `Get` call for `PlaybackStatus` with Bustle, which somehow seems to know that its signature is s:

![image](https://github.com/tmds/Tmds.DBus/assets/975131/7b21b694-ca67-4720-b640-21a1ce4af399)

Doing the same for VLC shows a variant type:

![image](https://github.com/tmds/Tmds.DBus/assets/975131/687293cf-e264-4f58-bae9-3d1bcf575938)

**Comment by tmds** [comment]
> I did check the Get call for PlaybackStatus with Bustle, which somehow seems to know that its signature is s:

Yes, the reply message for the request contains a signature header. For `Properties.Get` this signature should always be `v` for variant. For `Finamp` it replies with `s` since it put the string directly into the message.

Something like this should work to deal with that:

```cs
static string ReadMessagePlaybackStatus(Message message, MprisObject _)
{
    if (message.Signature == "s"u8)
    {
        var reader = message.GetBodyReader();
        return reader.ReadString();
    }
    else
    {
        return ReadMessage_v_s(message, _);
    }
}

public Task<string> GetPlaybackStatusAsync()
    => this.Connection.CallMethodAsync(CreateGetPropertyMessage(__Interface, "PlaybackStatus"), (Message m, object? s) => ReadMessagePlaybackStatus(m, (MprisObject)s!), this);
```

**Comment by DomiStyle** [comment]
Thanks, the comparison `message.Signature == "s"u8` doesn't work but `message.Signature` is `s` so that seems to be a viable solution.

I'm going to report this on Finamps Github as well, not sure which library they are using but the MPRIS implementation definitely needs some work.
