### ISSUE TITLE
Incorrectly generated names for properties inside of classes attributed with `Dictionary` when returned from `GetAll`

### ISSUE THREAD

**Issue by Rune580** [tmds/Tmds.DBus#299]
When a class is attributed with `Dictionary` the properties get incorrectly generated names when `GetAll` is called, for example
```csharp
[Dictionary]
public class MediaPlayer2Properties
{
    public bool CanQuit = false;
    public bool Fullscreen = false;
    public bool CanSetFullscreen = false;
    public bool CanRaise = false;
    public bool HasTrackList = false;
    public string Identity = "MusicDrone";
    public string DesktopEntry = "";
    public string[] SupportedUriSchemes = [];
    public string[] SupportedMimeTypes = [];
}
```
```csharp
public class MediaPlayerObject : IMediaPlayer2, IPlayer
{
    // ...

    private MediaPlayer2Properties _mediaPlayer2Properties;

    // ...

    Task<MediaPlayer2Properties> IMediaPlayer2.GetAllAsync()
    {
        return Task.FromResult(_mediaPlayer2Properties);
    }
}
```
Each field gets a generated name like `'<CanQuit>k__BackingField': <false>`. the full dump of the return is as follow
![Screenshot_20240804_133026](https://github.com/user-attachments/assets/6e8df160-d4c9-4fa6-bc53-2d377a7a6d2a)

Removing the `Dictionary` attribute, and modifying the `GetAll` method to return `IDictionary<string, object>` instead provides the correct names.
```csharp
public class MediaPlayer2Properties
{
    public bool CanQuit = false;
    public bool Fullscreen = false;
    public bool CanSetFullscreen = false;
    public bool CanRaise = false;
    public bool HasTrackList = false;
    public string Identity = "MusicDrone";
    public string DesktopEntry = "";
    public string[] SupportedUriSchemes = [];
    public string[] SupportedMimeTypes = [];
}
```
```csharp
public class MediaPlayerObject : IMediaPlayer2, IPlayer
{
    // ...

    private MediaPlayer2Properties _mediaPlayer2Properties;

    // ...

    Task<IDictionary<string, object>> IMediaPlayer2.GetAllAsync()
    {
        return Task.FromResult<IDictionary<string, object>>((Dictionary<string, object>)_mediaPlayer2Properties);
    }
}
```
![Screenshot_20240804_133151](https://github.com/user-attachments/assets/5d14f3f7-d02b-4d02-abb5-7154976670f6)

I assume this wasn't ever caught before due to the sort of niche use case. But the workaround is **required** in order to be in spec for `org.mpris.MediaPlayer2`, I was struggling to get my service recognized without the workaround.

**Comment by tmds** [comment]
> Each field gets a generated name like '<CanQuit>k__BackingField': <false>.

I'm not sure where these backing fields come from.

Could it be that you had the members in `MediaPlayer2Properties` declared as properties instead of fields?

**Comment by Rune580** [comment]
well this is embarrassing, this seems to be entirely my own fault. closing. sorry about that :/
