### ISSUE TITLE
Variant: support passing as an opaque value

### ISSUE THREAD

**Issue by tmds** [tmds/Tmds.DBus#303]
This is to enable reading a variant so it can be written back without the user knowing what was actually stored in the variant.

**Comment by tmds** [comment]
@ash-microconnect would this API enable [your use-case](https://github.com/tmds/Tmds.DBus/issues/282#issuecomment-2398057597):

```cs
struct Variant
{
  public Variant(VariantValue value);
```

**Comment by ash-microconnect** [comment]
It looks like it should. Would I have to manually convert received data from `VariantValue` to `Variant` (for example, with methods of signature `a{sv}`)?

**Comment by dmrayt** [comment]
have the same problem as @ash-microconnect . I need to read NetworkManager settings modify them and write them back.
Converting VariantValue to Variant could help, but I think only one Variant type for reading and writing would be better on the long term.

**Comment by tmds** [comment]
> Converting VariantValue to Variant

This should be pretty do-able. This is open for contribution if you want to take a shot at it.

> one Variant type for reading and writing would be better on the long term.

The `Variant` and `VariantValue` now deal with two separate concerns (one is serialization, the other is providing an introspectable value). The single unified type would have to tackle both together. The type would also need to be NativeAOT safe. I will think about it (when I have some more time than I currently do) and I'm also open to suggestions.

**Comment by tmds** [comment]
> This should be pretty do-able. This is open for contribution if you want to take a shot at it.

If someone decides to take a crack at this, as part of the implementation there should be a method on `VariantValue` that looks like:
```cs
internal unsafe void WriteTo(ref MessageWriter writer);
```

I will have some time to look into this further next month (mid/end of the month).

**Comment by tmds** [comment]
> I think only one Variant type for reading and writing would be better on the long term.

https://github.com/tmds/Tmds.DBus/pull/316 will enable `VariantValue` to be used both for reading/writing variant values from/to the bus.

**Comment by tmds** [comment]
@ash-microconnect @dmrayt can you try out the CI package (from https://www.myget.org/F/tmds/api/v3/index.json) and check it enables your use-case?

If you are using a code-generator, you can search and replace `Variant` with `VariantValue`.

With [Tmds.DBus.SourceGenerator](https://github.com/affederaffe/Tmds.DBus.SourceGenerator) you can obtain the generated code using the `EmitCompilerGeneratedFiles` (and `CompilerGeneratedFilesOutputPath`) properties as described in https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/. Once you have the code, disable the generator and do a search and replace.

If you are using the Tmds.DBus.Tool you can search and replace in the existing generated code. Or you generate it from scratch using a CI build (install with: dotnet tool update -g Tmds.DBus.Tool --prerelease --add-source https://www.myget.org/F/tmds/api/v3/index.json).

**Comment by ash-microconnect** [comment]
I wasn't able to use your CI package, but by compiling `Tmds.Dbus.Protocol` from source and then following your instructions, I was able to successfully perform my use case. Thank you for making this change!

**Comment by tmds** [comment]
Great! I'll work towards including this in a release by the end of this week.

**Comment by dmrayt** [comment]
I wil not have time to test it this week. But I have the same use case as ash-micronnect, if it works for him, it will also work for me.

**Comment by tmds** [comment]
This is part of the 0.21.0 release, which was just uploaded to nuget.org.
