### ISSUE TITLE
dbus codegen IdleMonitor and SafeHandle parameterless constructor

### ISSUE THREAD

**Issue by altenstedt** [tmds/Tmds.DBus#305]
Commit 1f82e0b9 from PR #289 (release 0.19.0) breaks the code generated by:

```sh
dotnet dbus codegen --protocol-api --service org.gnome.Mutter.IdleMonitor
```

> Error CS0310 : 'SafeHandle' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'Reader.ReadHandle<T>()'

```c#
protected static SafeHandle? ReadMessage_h(Message message, IdleMonitorObject _)
{
    var reader = message.GetBodyReader();
    return reader.ReadHandle<System.Runtime.InteropServices.SafeHandle>();
}
```

https://github.com/altenstedt/flextime-net/blob/main/Flextime.Monitor/IdleMonitor.DBus.cs

How can I use `dbus codegen` for IdleMonitor using 0.19.0 or later?

**Comment by tmds** [comment]
> How can I use dbus codegen for IdleMonitor using 0.19.0 or later?

You need to update the tool to a 0.19.0+ version.

It will use [SafeFileHandle](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.safehandles.safefilehandle?view=net-8.0) as the generic parameter. That change is included for the `codegen` command in the referenced PR.

This breaking change was made to match with the pattern .NET uses to create a `SafeHandle` in NativeAOT compatible code.
