### ISSUE TITLE
How to gen `org.mpris.MediaPlayer2` code?

### ISSUE THREAD

**Issue by Coloryr** [tmds/Tmds.DBus#306]
Like sample [Mpris.DBus.cs](https://github.com/tmds/Tmds.DBus/blob/main/samples/MediaPlayerRemote/Mpris.DBus.cs), how to get from codegen?

**Comment by tmds** [comment]
It was generated with steps as described in the https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#example.

Alternatively, there is a source-generator available: https://github.com/affederaffe/Tmds.DBus.SourceGenerator.

https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#code-generators lists both options.

**Comment by Coloryr** [comment]
> It was generated with steps as described in the https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#example.
> 
> Alternatively, there is a source-generator available: https://github.com/affederaffe/Tmds.DBus.SourceGenerator.
> 
> https://github.com/tmds/Tmds.DBus?tab=readme-ov-file#code-generators lists both options.

Nope, gen example counld't find any service like mpris

**Comment by tmds** [comment]
> gen example counld't find any service like mpris

You need to run a media player.

**Comment by Coloryr** [comment]
> > gen example counld't find any service like mpris
> 
> You need to run a media player.
Already running
![image](https://github.com/user-attachments/assets/24a296f5-147f-44ee-83e5-2ef0d2b927b0)
![image](https://github.com/user-attachments/assets/d52d2a71-da44-4c4c-833e-ae8e8b3990bd)

**Comment by tmds** [comment]
> Already running

You need to run a media player that supports mpris and call `list services`.

![image](https://github.com/user-attachments/assets/6f889f24-c7ec-4b95-8db5-31f825220342)

**Comment by Coloryr** [comment]
Thanks, I see it.
