### ISSUE TITLE
Tmds.DBus.Tool missing on nuget?

### ISSUE THREAD

**Issue by Compufreak345** [tmds/Tmds.DBus#31]
Hi,

regarding to your doc I added this lines to my .csproj:
```
<PackageReference Include="Tmds.DBus" Version="*"/>
<DotNetCliToolReference Include="Tmds.DBus.Tool" Version="*" />
```

But on dotnet restore I get this error:

> /home/cs/Desktop/Telekom.DeMail/Source/TestManager.SystemdApi/TestManager.SystemdApi.csproj : error NU1101: Unable to find package Tmds.DBus.Tool. No packages exist with this id in source(s): CliFallbackFolder, nuget.org

Did this package get lost on nuget or am I doing anything wrong?

Thanks & best regards,
Christoph

P.S.: I'm using .Net Core 2.0.0 on Xubuntu 16.04

**Comment by tmds** [comment]
hi @Compufreak345 this package has not yet made it onto NuGet. A release will probably come next week or the week after. You can pick the package from this myget feed in the meanwhile:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="Tmds.Posix" value="https://www.myget.org/F/tmds/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by tmds** [comment]
On NuGet as of today :)
