### ISSUE TITLE
Property ending with anothers full name

### ISSUE THREAD

**Issue by csnewman** [tmds/Tmds.DBus#43]
While using the auto generated code for the system service "org.freedesktop.systemd1" (created by the tool), I came across an issue with how the MessageReader handles property matching.

The generated ManagerProperties class has two properties:
FinishedTimestamp and SecurityFinishTimestamp

However the handling inside the message reader throws an exception

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Tmds.DBus.Protocol.MessageReader.ReadDictionaryObject[T]()
   at Tmds.DBus.CodeGen.DBusObjectProxy.<CallNonVoidMethodAsync>d__9`1.MoveNext()
```

I have narrowed it down to the following code block:
https://github.com/tmds/Tmds.DBus/blob/8ff9eb870fc3ae4d9fa005697f64910c3908a337/src/Tmds.DBus/Protocol/MessageReader.cs#L402-L404

The endswith handling is causing the lookup for FinishedTimestamp to find two possible bindings, FinishedTimestamp and SecurityFinishTimestamp.

**Comment by tmds** [comment]
Actually, the issue is there are some missing parentheses.
`f.Name.EndsWith(key) || (key.Contains("-") && f.Name.Replace('_', '-').EndsWith(key))` must be grouped as a condition.
When that is `true`, the && logic behind it needs to kick out `SecurityFinishTimestamp`:
```
((f.Name.Length == key.Length) || 
 (f.Name.Length == key.Length + 1 && f.Name[0] == '_'))
```

**Comment by tmds** [comment]
This is in 0.6.0 on nuget.org.
