### ISSUE TITLE
Introspection does not include Introspect interface in response

### ISSUE THREAD

**Issue by csnewman** [tmds/Tmds.DBus#47]
The current IntrospectionWriter does not write the interface implementation of the "org.freedesktop.DBus.Introspectable" interface.

```
<node name="/">
  <interface name="example">
    <method name="some method">
      <arg direction="out" name="value" type="s"/>
    </method>
  </interface>
</node>
```
However the following should also be included

```
   <interface name="org.freedesktop.DBus.Introspectable">
     <method name="Introspect">
       <arg direction="out" type="s" />
     </method>
   </interface>
```

I believe also "org.freedesktop.DBus.Peer" should be returned as both of these interfaces are hard coded as being implemented for all types in Tmds.DBus. "org.freedesktop.DBus.Properties" should probably be optional.

I do not currently see a way to manually expose that these interfaces are implemented in the introspection data response?

**Comment by tmds** [comment]
> "org.freedesktop.DBus.Introspectable"
> "org.freedesktop.DBus.Peer"

We want to adopt the common behavior as other implementations. If it is common to include this, then we'll do the same.

> "org.freedesktop.DBus.Properties" should probably be optional

In what way is it not optional?

**Comment by csnewman** [comment]
As far as I have seen, using d-feet to Inspect other system services, they all Include the introspective and peer interfaces on all of their objects, but not every object lists the properties interface.

**Comment by csnewman** [comment]
Any object that has properties lists the Interface as far as I can tell.

However, currently tmds.dbus does not list the interface.

**Comment by tmds** [comment]
> Any object that has properties lists the Interface as far as I can tell. Any that do not have any properties, doesn't list the interface.

That makes sense. We'll do the same.

**Comment by tmds** [comment]
Fixed in https://github.com/tmds/Tmds.DBus/pull/51

**Comment by tmds** [comment]
This is in 0.6.0 on nuget.org.
