### ISSUE TITLE
Consider publishing an updated NuGet package with recent fixes

### ISSUE THREAD

**Issue by Martin-Bohring** [tmds/Tmds.DBus#50]
Hello,
I am a beginning user of your library (and very much like it)
Recently I have hit  issue #43, because two properties have the same name ending (EDID and ID in my case)

Are there any plans to publish an updated NuGet with the fixes included?

If I can help with that please let me know.

**Comment by tmds** [comment]
hi @Martin-Bohring I just published 0.6.0 to nuget.org which includes that fix.

**Comment by Martin-Bohring** [comment]
Thanks for the fix. We tried out the new Nuget package and it works like a charm
