### ISSUE TITLE
How to create a D-Bus Service with Tmds.DBus (RegisterServiceAsync) ?

### ISSUE THREAD

**Issue by Ticoel** [tmds/Tmds.DBus#59]
Hello !

I wish to create a service of the type of dbus using your library but the RegisterServiceAsync method send me a lot of exceptions as "Tmds.DBus.DBusException: org.freedesktop.DBus.Error.AccessDenied".

Is it the good method for this? How to use this method?

**Edit: I have succeeded in correcting the previous error in editing policy, but I am curious about a good implantation of RegisterServiceAsync and ActivateServiceAsync methods.**

Thank you for your help.

My actual research code executed on Raspberry Pi 3.

This is a systemd service file:
```
[Unit]
Description=Robot Communication

[Service]
Type=dbus
BusName=org.RobotCom.service
ExecStart=/bin/bash /home/nicolas/run.sh
```

This is a dbus service file:
```
[D-BUS Service]
Name=org.RobotCom.service
Exec=/bin/false
User=root
SystemdService=RobotCom.service

```

This is a executable:
```
static async Task Main(string[] args)
{
	using (var connection = new Connection(Address.System))
	{
		await connection.ConnectAsync();

		await connection.RegisterServiceAsync("org.RobotCom.service", ServiceRegistrationOptions.None);

		while (true)
		{
			await connection.ActivateServiceAsync("org.RobotCom.service");
		}
	}
}
```

**Comment by tmds** [comment]
hi @Ticoel 

The application that provides the service looks like:
```
Main:
connection.ConnectAsync
connection.RegisterObject(s)Async
connection.RegisterServiceAsync
while (true) { await Task.Delay(int.MaxValue) }
```
An application that consumes the service calls `ActivateServiceAsync`.

**Comment by tmds** [comment]
Did you get this to work?

**Comment by Ticoel** [comment]
Hi @tmds !

Yes, this is work.

Thank you.
