### ISSUE TITLE
Cannot generate code from Bluez LEAdvertisingManager1

### ISSUE THREAD

**Issue by scegg** [tmds/Tmds.DBus#67]
when trying to run dotnet dbus codegen --bus system --service org.bluez.LEAdvertisingManager1, an exception is thrown:
Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez.LEAdvertisingManager1 was not provided by any .service files

org.bluez.LEAdvertisingManager1 is listed and visible in org.bluez, object path /org/bluez/hci0.

Any idea?
Thanks.

**Comment by tmds** [comment]
`ServiceUnknown` -> is there a service with that name on the system bus?

**Comment by scegg** [comment]
actually I dont know.

The service could be observed by d-feet, provided by bluez.

Here is the file written by some other: https://github.com/brookpatten/Mono.BlueZ/blob/master/Mono.BlueZ.DBus/LEAdvertisingManager1.cs

**Comment by tmds** [comment]
You can use the tool to list services, see https://github.com/tmds/Tmds.DBus/blob/master/docs/tool.md#list

**Comment by tmds** [comment]
Probably this is the service name:
private const string SERVICE = "org.bluez";

**Comment by scegg** [comment]
Yes it can be listed. Both command below have output.

dotnet dbus list services --bus system
dotnet dbus list objects --bus system --service org.bluez.LEAdvertisingManager1

**Comment by scegg** [comment]
> Probably this is the service name:
> private const string SERVICE = "org.bluez";

I guess I tried this but not so sure. Currently, I have no connection to that computer, I will test it again and update this issue about 14 hrs later.

**Comment by scegg** [comment]
You are correct. Here is the detail log.

$ dotnet dbus list services --bus system | grep bluez
org.bluez

$ dotnet dbus list objects --bus system --service org.bluez.LEAdvertisingManager1
exception

$ dotnet dbus list objects --bus system --service org.bluez
/ : org.freedesktop.DBus.ObjectManager
/org/bluez : org.bluez.AgentManager1 org.bluez.ProfileManager1
/org/bluez/hci0 : org.bluez.Adapter1 org.bluez.GattManager1 org.bluez.LEAdvertisingManager1 org.bluez.Media1 org.bluez.NetworkServer1

$ dotnet dbus codegen --bus system --service org.bluez
generated.

Thanks a lot.
