### ISSUE TITLE
How to write an object for dbus?

### ISSUE THREAD

**Issue by scegg** [tmds/Tmds.DBus#68]
Hi.

I'm in the same problem like https://github.com/tmds/Tmds.DBus/issues/58.

The LEAdvertisement1 is not generated by CLI tools. Here is the doc of this file: https://github.com/hadess/bluez/blob/master/doc/advertising-api.txt

I wrote a file (LEAdvertisement1) **by guessing** due to no doc/demo here.

But when I run it, I got an exception while calling RegisterObjectAsync:
```
Cannot adaptor class for generic method System.Threading.Tasks.Task`1[T] GetAsync[T](System.String). Refactor the method to return Task<object>.) ---> System.NotImplementedException: Cannot adaptor class for generic method System.Threading.Tasks.Task`1[T] GetAsync[T](System.String). Refactor the method to return Task<object>.
   at Tmds.DBus.CodeGen.DBusAdapterTypeBuilder.ImplementConstructor(TypeDescription typeDescription)
   at Tmds.DBus.CodeGen.DBusAdapterTypeBuilder.Build(Type objectType)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetExportTypeInfo(Type objectType)
   at Tmds.DBus.Connection.RegisterObjectsAsync(IEnumerable`1 objects)
```

Here is the test app:
[Test1.zip](https://github.com/tmds/Tmds.DBus/files/3289538/Test1.zip)

**Comment by tmds** [comment]
The `dotnet dbus codegen` command can also accept an xml file as it's argument.

So you can try to find one (for example [on Github](https://github.com/search?l=XML&q=LEAdvertisement1&type=Code)) and pass it to the command.

Does that work for you?

CC @dodgyrabbit

**Comment by scegg** [comment]
Thanks for your reply.
The problem is BLUEZ only required the object must implement an interface. But it seems that Tmds.DBus required more about property operatings.

**Comment by tmds** [comment]
This describes how properties are modelled: https://github.com/tmds/Tmds.DBus/blob/master/docs/modelling.md#properties

**Comment by scegg** [comment]
Yes, that was I tried to do. But it seems that I did something wrong.

**Comment by tmds** [comment]
Try using signatures like this:
https://github.com/tmds/Tmds.DBus/blob/fbf3b7d0a5cf6d0f87145137e116ca98d07c5399/test/Tmds.DBus.Tests/IPropertyObject.cs#L8-L15

**Comment by tmds** [comment]
The exception is about the `GetAsync` method and it says what the fix is:

> Refactor the method to return Task\<object>.

**Comment by scegg** [comment]
Too many properties need to be wrapped. I’ll make a converter tool to do that later and test.

**Comment by scegg** [comment]
Sorry, I give up.
Too many code for converting the interface for Tmds.Dbus standards.
Thanks for your help.

**Comment by tmds** [comment]
Why not use reflection:
```
        public Task<object> GetAsync(string prop)
            => Task<object>.FromResult(this.GetType().GetProperty(prop).GetValue(this));
```

**Comment by scegg** [comment]
> Why not use reflection:
> 
> ```
>         public Task<object> GetAsync(string prop)
>             => Task<object>.FromResult(this.GetType().GetProperty(prop).GetValue(this));
> ```

The major problem is involved with WatchPropertiesAsync.

I was planed to extend netcore app on linux to Bluetooth LE functions with BLUEZ and DBus. Due to too much time cost on this and no plain plan view yet, these functions are removed from the product milestone. Thanks for your help. Maybe I'll get back here next year.
