### ISSUE TITLE
Example Watch code doesn't dispose?

### ISSUE THREAD

**Issue by beevik** [tmds/Tmds.DBus#74]
You have the following the sample code given in the README:
```csharp
foreach (var device in await networkManager.GetDevicesAsync())
{
    var interfaceName = await device.GetInterfaceAsync();
    await device.WatchStateChangedAsync(
        change => Console.WriteLine($"{interfaceName}: {change.oldState} -> {change.newState}")
    );
}
```

The `WatchStateChangedAsync` method returns a `Task<IDisposable>`, but I don't see any code disposing the return value.  Is it necessary to dispose the value returned from a watch call?

**Comment by tmds** [comment]
> Is it necessary to dispose the value returned from a watch call?

Dispose is the way you unsubscribe from the event.
