### ISSUE TITLE
"Profile1" "NewConnection" "doesn't exist"

### ISSUE THREAD

**Issue by vindicatorr** [tmds/Tmds.DBus#80]
I've been using some guidance like https://github.com/brookpatten/Mono.BlueZ/blob/b4a1dfd5b662d1e9365b12cbdb843a3dffd72e20/Mono.BlueZ.Console/PebbleBootstrap.cs along with https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/profile-api.txt and your https://github.com/tmds/Tmds.DBus/blob/master/docs/modelling.md#properties.

I was originally starting with just trying 'lDevice.ConnectProfileAsync("00001101-0000-1000-8000-00805f9b34fb")' (for SPP/Serial using an HC-05).
But while watching the "btmon" output, It was connecting, then disconnecting supposedly from my system's own request: "< ACL Data TX...L2CAP: Disconnection Request".

I'm guessing that something else needs to be done in order for my program/system/bluez to not think the job is done yet like attaching to a filestream.

That's when I tried to modify that old Pebble demo, but your error told me that's no good since I was using the stateless autoconnect method, which had RegisterObjectAsync lead me to your https://github.com/tmds/Tmds.DBus/blob/master/docs/howto.md.
But I don't think I was doing that right either.

I finally got to making my own:
```
[Tmds.DBus.DBusInterface("org.bluez.Profile1")]
    public interface IProfile1 : Tmds.DBus.IDBusObject
    {
        public System.Threading.Tasks.Task ReleaseAsync();
        public System.Threading.Tasks.Task NewConnectionAsync(Tmds.DBus.ObjectPath Device, Tmds.DBus.CloseSafeHandle Fd, System.Collections.Generic.IDictionary<string, object> FdProperties);

        public System.Threading.Tasks.Task RequestDisconnectionAsync(Tmds.DBus.ObjectPath pDeviceObjectPath);
    }

    public class Profile1 : ns.IProfile1
    {
        private System.IO.FileStream gFileStream;
        private Tmds.DBus.ObjectPath gObjectPath;

        Tmds.DBus.ObjectPath Tmds.DBus.IDBusObject.ObjectPath
        {
            get
            {
                return this.gObjectPath;
            }
        }
        //  => throw new NotImplementedException();

        public Profile1()
        {
            this.gObjectPath = new Tmds.DBus.ObjectPath("/profiles");
        }

        async System.Threading.Tasks.Task IProfile1.ReleaseAsync()
        {
            await System.Threading.Tasks.Task.Delay(1000);
        }


        async System.Threading.Tasks.Task IProfile1.NewConnectionAsync(Tmds.DBus.ObjectPath Device, Tmds.DBus.CloseSafeHandle Fd, System.Collections.Generic.IDictionary<string, object> FdProperties)
        {
            await System.Threading.Tasks.Task.Delay(1000);
            // throw new NotImplementedException();
        }

        async System.Threading.Tasks.Task IProfile1.RequestDisconnectionAsync(Tmds.DBus.ObjectPath pDeviceObjectPath)
        {
            if (!(gFileStream is null))
            {
                gFileStream.Close();
                gFileStream.Dispose();
            }
            await System.Threading.Tasks.Task.Delay(1000);
            // throw new NotImplementedException();
        }
    }
```
along with:
```
            System.Collections.Generic.Dictionary<System.String, System.Object> lOptions = new System.Collections.Generic.Dictionary<string, object>();
            lOptions.Add("Name", "testbluetoothname");
            lOptions.Add("Channel", (System.UInt16)22);
            lOptions.Add("PSM", (System.UInt16)22);
            lOptions.Add("Role", "client");
            lOptions.Add("Service", "00001101-0000-1000-8000-00805f9b34fb");
            this.gProfileManager1.RegisterProfileAsync(new Tmds.DBus.ObjectPath("/profiles"), "00001101-0000-1000-8000-00805f9b34fb", lOptions).Wait();
```
and:
```
lDevice.ConnectProfileAsync("00001101-0000-1000-8000-00805f9b34fb").Wait(5000);
```
after initializing things like:
```
this.gSystemConnection = Tmds.DBus.Connection.System;
this.gProfile1 = this.gSystemConnection.CreateProxy<ns.IProfile1>("org.bluez", new Tmds.DBus.ObjectPath("/org/bluez"));
this.gProfileManager1 = this.gSystemConnection.CreateProxy<bluez.DBus.IProfileManager1>("org.bluez", new Tmds.DBus.ObjectPath("/org/bluez"));
```
But that only got me to my latest error: '= bluetoothd: testbluetoothname replied with an error: org.freedesktop.DBus.Error.UnknownMethod, Method "NewConnection" with signature "oha{sv}" on interface "org.bluez.Profile1" doesn't exist'.

Does anything stand out to you that makes you think "man, what are you even doing?"?
I'd think the "oha{sv}" matches up correctly with my NewConnection implementation with the parameters Objectpath(=o), CloseSafeHandle(=h), IDictionary<string, object>(=a{sv}), and the proxy was created for Profile1.

I have a breakpoint at NewConnection, waiting for that to be hit, but it never happens, and I'm assuming it's because I'm doing things wrong or am missing something.
I also know my NewConnection function is incomplete. It's basically just a stub until the breakpoint hits. Then I'll finish the rest.

**Comment by vindicatorr** [comment]
I've got a lead I think. It doesn't appear to be an issue with Tmds, but more likely a threading/task/timing race-related issue.

I had my debugger paused for quite awhile, then came back and ran it the rest of the way and the NewConnection breakpoint was hit and "btmon" showed "org.freedesktop.DBus.Error.NoReply" this time which is a great lead.

**Comment by MrRadian** [comment]
Hi, Can u tell how u resolve this problem, i have the same error "replied with an error: org.freedesktop.DBus.Error.UnknownMethod, Method "NewConnect.. ", and i don't know to what to do
