### ISSUE TITLE
Add `, CancellationToken ct = default)` at the end of every async Task API.

### ISSUE THREAD

**Issue by Vinigas** [tmds/Tmds.DBus#84]
E.g. instead of `public async Task ConnectAsync(dynamic? myParams)` to `public async ValueTask ConnectAsync(dynamic? dmyParams, CancellationToken ct = default)`.
CancellationToken has props/methods like IsCancellationRequested , ThrowIfCancellationRequested() which could be used throughout this library.

This would allow to just cancel to D-Bus message request writing (big packets) or reading/waiting result, if that is not actual anymore. Also would useful to cancel/dispose D-Bus watches (instead of current Task<IDisposable> returned API).

`, CancellationToken ct = default)` would be almost fully backward-compatible with current api. Maybe I will make pull-request with these changes, if I have time to.

**Comment by tmds** [comment]
I considered this, but I felt it is not semantically correct because the operation is not cancelled. When I need this, I do this by using a `WaitAsync` extension method on `Task` that takes a timeout. It is more explicit that this cancels the waiting, and not the operation itself.

**Comment by maciej-napora** [comment]
What are the chances of waiting being unbound and the task created by making a DBus call, using generated interface, never terminating. I wonder if this would cause memory leak in a long running application.
