### ISSUE TITLE
Missing ConfigureAwait(false)

### ISSUE THREAD

**Issue by tibel** [tmds/Tmds.DBus#87]
Today I was analyzing a nasty deadlock issue in our code together with this library.
Finally I found and fixed the issue in our code, but I fear there might be other usages that might potentially deadlock.

No `await` in this library is followed by `ConfigureAwait(false)` as suggested for libraries.
Is there any reason for that?

And if not, are you willing to accept a pull request that adds `ConfigureAwait(false)` to all awaits?

**Comment by tmds** [comment]
> are you willing to accept a pull request that adds ConfigureAwait(false) to all awaits?

Yes, is https://github.com/tmds/Tmds.DBus/pull/86 related?

**Comment by tibel** [comment]
> Yes, is #86 related?

No, not the issue I faced. Just saw it and thought it should be changed.
