### ISSUE TITLE
org.bluez.Profile1 problem

### ISSUE THREAD

**Issue by MrRadian** [tmds/Tmds.DBus#88]
Hi from a couple day i try to make connection with bluez via Dbus. I can register profile by ProfileManager1 but when I connect bluetoothd gives me an error: org.freedesktop.DBus.Error.UnknownMethod, Method "NewConnection" with signature "oha{sv}" on interface "org.bluez.Profile1" doesn't exist'.

My Profile1 interface looks like :
`[DBusInterface("org.bluez.Profile1")]
public interface IProfile1 : IDBusObject
    {
        Task ReleaseAsync();
        Task RequestDisconnectionAsync(ObjectPath device);
        Task NewConnectionAsync(ObjectPath path, CloseSafeHandle fd, IDictionary<string, ushort> dict);
    }`
so everything looks ok.

Can you provide a example of correct profile registration and connection, to trigger NewConnectionAsync?

**Comment by MrRadian** [comment]
Hi, I manage to get NewConnection. I study other examples of RegisterProfile from ProfileManager1 and in each before register profile we have to register IProfile object. So we have to create
`public class Profile : IProfile1`. 

Before i did the same but I always got an error from Connection() with AutoConnect. I tried idea  #https://github.com/tmds/Tmds.DBus/issues/80 and that was almost the right approach. But it missed IProfile object registration. Other c# dbus api have registration func, Tmds.Dbus have it to but it gives me AutoConnect error. I don't know why but using:
`Connection conn = new Connection(Address.System);`
`await conn.ConnectAsync();` 
gives no error, and I get reply form NewConnection.

I will paste my code because it was real pain in ass for me.

    [DBusInterface("org.bluez.Profile1")]
    public interface IProfile1 : IDBusObject
    {
        Task ReleaseAsync();
        Task RequestDisconnectionAsync(ObjectPath device);
        Task NewConnectionAsync(ObjectPath path, CloseSafeHandle fd, IDictionary<string, object> dict);
    }
    public class Profile : IProfile1
    {
        
        public Profile(string Path)
        {
            ObjectPath = new ObjectPath(Path);
        }

        public Task ReleaseAsync()
        {
            return Task.Delay(1000);
        }

        public Task RequestDisconnectionAsync(ObjectPath device)
        {
            Console.WriteLine("Disconnect");
            return Task.Delay(1000);
        }

        public Task NewConnectionAsync(ObjectPath path, CloseSafeHandle fd, IDictionary<string, object> dict)
        {
            Console.WriteLine("Welcome in NewConnection :)");
            return Task.Delay(1000);
        }

        public ObjectPath ObjectPath { get; }
    }
    public class BtProfile
    {
        private IProfileManager1 _profileManager1;
        private Profile mainProfile;
        private string uuid = "234381d4-75aa-11ea-bc55-0242ac130003";
        private Connection conn;
        private readonly IDictionary<string, object> _dictionary = new Dictionary<string, object>
        {
            { "Name", "BarmanServer"},
            { "AutoConnect", true },
            { "Channel", (ushort)2},
            { "Role", "server" },
            { "RequireAuthentication", false },
            { "RequireAuthorization", false }
        };

        public async Task CreateProfile()
        {
            try
            {
                conn = new Connection(Address.System);
                await conn.ConnectAsync();

                mainProfile = new Profile("/org/bluez/profile");
                await conn.RegisterObjectAsync(mainProfile);
                
                Console.WriteLine("Create and register Profile1 object");
                await Task.Delay(2000);
            

                _profileManager1 = conn.CreateProxy<IProfileManager1>("org.bluez", "/org/bluez");
                await _profileManager1.RegisterProfileAsync("/org/bluez/profile", uuid, _dictionary);
                Console.WriteLine("Register profile form IProfilManager1");
                await Task.Delay(1000);
                
            }
            catch (Exception e)
            {
                Console.WriteLine("Error" + e.Message);
            }
        }
    }

Hope it will helps anyone with similar problem.

**Comment by Merely-chao** [comment]
Hi,
 I used your example to implement the proxy for Bluetooth pairing, but it didn't work, although there was no exception. I hope to get your help. Thank you very much!
The proxy class is not called when pairing with the phone.



 ` 
[DBusInterface("org.bluez.Agent1")]
    public interface IAgent1 : IDBusObject
    {
        Task ReleaseAsync();
        Task<string> RequestPinCodeAsync(ObjectPath device);
        Task DisplayPinCodeAsync(ObjectPath device, string pincode);

        Task<int> RequestPasskeyAsync(ObjectPath device);

        Task DisplayPasskeyAsync(ObjectPath device, int passkey,
                                ushort entered);
        Task RequestConfirmationAsync(ObjectPath device, int passkey);
        Task RequestAuthorizationAsync(ObjectPath device);

        Task AuthorizeServiceAsync(ObjectPath device, string uuid);
        Task CancelAsync();

    }

 public class Agent : IAgent1
    {
        public Agent()
        {
            ObjectPath = "/org/bluez/agent";
        }
        public ObjectPath ObjectPath { get; }

        public Task AuthorizeServiceAsync(ObjectPath device, string uuid)
        {
            return BlueZManager.WriteTxt($"{device}:{uuid}");
         //   return Task.Delay(100);
        }

        public Task CancelAsync()
        {
            return BlueZManager.WriteTxt($"CancelAsync");
        }

        public Task DisplayPasskeyAsync(ObjectPath device, int passkey, ushort entered)
        {
            return BlueZManager.WriteTxt($"{device}:{passkey}:{entered}");
        }

        public Task DisplayPinCodeAsync(ObjectPath device, string pincode)
        {
            return BlueZManager.WriteTxt($"{device}:{pincode}");
        }

        public Task ReleaseAsync()
        {
            return BlueZManager.WriteTxt($"ReleaseAsync");
        }

        public Task RequestAuthorizationAsync(ObjectPath device)
        {
            return BlueZManager.WriteTxt($"RequestAuthorizationAsync{device}");
        }

        public Task RequestConfirmationAsync(ObjectPath device, int passkey)
        {
            return BlueZManager.WriteTxt($"RequestConfirmationAsync{device}:{passkey}");
        }


public static async Task SetDefaultAgent(Agent agent)
        {


            conn = new Connection(Address.System);

            var infos = await conn.ConnectAsync();

            var agentManager = conn.CreateProxy<IAgentManager1>(BluezConstants.DbusService, "/org/bluez");
            await conn.RegisterObjectAsync(agent);
            await Task.Delay(2000);
            await agentManager.RegisterAgentAsync(agent.ObjectPath, "KeyboardDisplay");

            await Task.Delay(1000);
            await agentManager.RequestDefaultAgentAsync(agent.ObjectPath);

            // var testagent = conn.CreateProxy<IAgent1>(infos.LocalName, agents.ObjectPath);
            //await testagent.ReleaseAsync();

        }`
