### ISSUE TITLE
The maximum number of pending replies per connection has been reached Error

### ISSUE THREAD

**Issue by kiyoungsong** [tmds/Tmds.DBus#91]
Hello.
Sorry, actually i showed this Error from Bluez and i couldn't find any solution. 
But it referenced Tmds.DBus so i am writing a question.
I have tried to read values for BLE Device on Raspberry through Bluez which is using Tmds.DBus.
But sometimes it showed “The maximum number of pending replies per connection has been reached” after that when I call a method seems like DBus never reply like pausing.
When DBus showed that message and then I tried to call DBus method does DBus doesn’t work?
If it is do you know  how to solution?

**Comment by tmds** [comment]
I think it means your client has `max_replies_per_connection` on-going requests, see https://dbus.freedesktop.org/doc/dbus-daemon.1.html.

**Comment by tmds** [comment]
Question is answered, closing.
