### ISSUE TITLE
DBus Reciever will not recieve messages from producer

### ISSUE THREAD

**Issue by TauAkiou** [tmds/Tmds.DBus#92]
I am doing a simple project using DBus, and I implemented the producer model from https://github.com/tmds/Tmds.DBus/issues/62. This code will successfully start pushing signals onto the bus once every 10 seconds. I can verify this behavior using Bustle and other command line tools.

All I'm attempting to do is produce a message on the producer side, then recieve it on the consumer side. I'm using Signals to do this.

However, my receiver, despite using the same interface, does not see or respond to any of the signals on the DBus.

Both the producer and consumer are C# programs running .NET Core 3.

Producer:
```       
public static async Task MainAsync(string[] args)
        {
            using (Connection conn = new Connection(Address.Session))
            {
                await conn.ConnectAsync();
                var obj = new IPCLink();
                await conn.RegisterObjectAsync(obj);
                await conn.RegisterServiceAsync("org.tauakiou.test", ServiceRegistrationOptions.None);

                var service = await conn.ListServicesAsync();

                //Task.Run(DBusEventListener);
                
                while (true)
                {
                    obj.ConnectLink = RandomString(8);
                    Console.WriteLine("Newstring:" + obj.ConnectLink);
                    Thread.Sleep(10000);
                }
            }
        }
```

Reciever:
```
        static async Task MainAsync(string[] args)
        {
            using (Connection conn = new Connection(Address.Session))
            {
                await conn.ConnectAsync();

                var list = await conn.ListServicesAsync();

                var test = conn.CreateProxy<IConnectLink>("org.tauakiou.test",
                    "/org/tauakiou/test");

                var test2 = test as IConnectLink;

                await test.WatchPropertiesAsync(OnPropertiesChanged);
                
                while (true)
                {
                    await Task.Delay(int.MaxValue);
                }
            }
        }

        // Despite being linked, OnPropertiesChanged is never called, despite the DBus being flooded with signals.
        private static void OnPropertiesChanged(PropertyChanges changes)
        {
           
            var t1 = changes.Changed.Length;
            var t2 = changes.Changed;

            Console.WriteLine("Received DBUS STRING: " + (string) t2[0].Value);
        }
```

Interface & Object:
```
    [DBusInterface("org.tauakiou.test")]
    public interface IConnectLink : IDBusObject
    {
        Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
    }

    public class IPCLink : IConnectLink
    {
        string _connectlink;
        public string ConnectLink
        {
            get { return _connectlink; }
            set 
            {
                _connectlink = value;
                OnPropertiesChanged?.Invoke(PropertyChanges.ForProperty(nameof(ConnectLink), value));
            }
        }
        public ObjectPath ObjectPath => new ObjectPath("/org/TauAkiou/test");
        public event Action<PropertyChanges> OnPropertiesChanged;

        public Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler)
        {
            return SignalWatcher.AddAsync(this, nameof(OnPropertiesChanged), handler);
        }
    }
```

I don't know if this is a problem, or a result of my lack of experience with DBus and the library.

**Comment by TauAkiou** [comment]
I figured it out - moving from the PropertiesChanged signal to a custom signal worked, though it would probably make more sense if I used a method. Closing.

**Comment by Lucia-Bader** [comment]
> I figured it out - moving from the PropertiesChanged signal to a custom signal worked, though it would probably make more sense if I used a method. Closing.

@TauAkiou Could you please give an example of how you realized the implementation with a custom signal?

**Comment by TauAkiou** [comment]
> > I figured it out - moving from the PropertiesChanged signal to a custom signal worked, though it would probably make more sense if I used a method. Closing.
> 
> @TauAkiou Could you please give an example of how you realized the implementation with a custom signal?

generally what I did was avoid using the OnPropertiesChanged event and instead just ran code with an embedded event. The functional DBus code I used is present here: https://github.com/TauAkiou/amonguscapture-gtk/tree/master/AmongUsCapture/IPC/DBus

I'm not sure what you're trying to do though, so this may or may not be sufficient for your workload.
