### ISSUE TITLE
Cannot adaptor class for generic method

### ISSUE THREAD

**Issue by grokys** [tmds/Tmds.DBus#93]
I'm getting the following error:

```
Cannot adaptor class for generic method System.Threading.Tasks.Task`1[T] GetAsync[T](System.String)
```

The method that seems to be causing the error is generated by the Tmds.DBus generator itself:

```
Task<T> GetAsync<T>(string prop);
```

And indeed is referenced in the docs:

https://github.com/tmds/Tmds.DBus/blob/master/docs/modelling.md#properties

Is there something I'm doing wrong here? The only other mention I can find of this [is here](https://github.com/tmds/Tmds.DBus/issues/68#issuecomment-508471910) and suggests to change the return value to `Task<object>`, but if that's the case why does the codegen produce the generic return type, and why do the docs mention it?

Oh, also I think there's a word missing in the error message: should it be "Cannot _generate_ adaptor class"?

**Comment by kptnk** [comment]
I experienced the same problem.

Implementing the generic `GetAsync<T>` works for accessing properties of interfaces from other applications using `Connection.CreateProxy`. Using `Connection.RegisterObjectAsync` throws the error for objects implementing an interface with properties.

Changing to the non-generic `GetAsync<object>` does no longer generate this error. But the interface does not provide its properties on the DBus (Signals and Methods work fine).

I also could use an example of how an interface and its implementing class should look, if I want to register an interface with properties on the DBus. Looking at https://github.com/tmds/Tmds.DBus/blob/master/test/Tmds.DBus.Tests/IPropertyObject.cs for directions did not help, which led me here. 

(I use Tmds.DBus on Ubuntu 20 and Mono 6)

**Comment by tmds** [comment]
> The method that seems to be causing the error is generated by the Tmds.DBus generator itself:

To register types with properties you need to change the method signature that gets output by the generator to:

```cs
Task<object> GetAsync(string prop);
```

> Oh, also I think there's a word missing in the error message: should it be "Cannot generate adaptor class"?

Yes.

> Looking at https://github.com/tmds/Tmds.DBus/blob/master/test/Tmds.DBus.Tests/IPropertyObject.cs for directions did not help, which led me here.

In what way was it not helpful? Did you see the related `PropertyObject` class?

**Comment by kptnk** [comment]
Implementing properties using the `IPropertyObject`  did not work as expected. 

I copied the `IPropertyObject` interface and the implementation in the `PropertyObject` class both into my test project. Created an instance of `PropertyObject` with a property named `"test"` and a value of `123u` (via the dictionary) and registered this object with `RegisterObjectAsync`. Then I registered the service with a name.

When examining the object with d-feet I can see only see an empty PropertyObject Interface without the  "test" property. I also can not see that the  `org.freedesktop.DBus.Properties` interface is implemented by the object (Peer and Introspectable are there).

Everything else - Methods and Signals (consuming and producing) - is working like a charm.

**Comment by tmds** [comment]
The docs need to improve...

This example may get you on your way:

```cs
    class Program
    {
        static async Task Main(string[] args)
        {
            var connection = new Connection(Address.Session);
            await connection.ConnectAsync();
            await connection.RegisterServiceAsync("tmds.test");
            await connection.RegisterObjectAsync(new PropertyObject());
            await Task.Delay(int.MaxValue);
        }
    }

    [Dictionary]
    public class MyProperties
    {
        public int Age;
        public string Name;
    }

    [DBusInterface("tmds.dbus.tests.PropertyObject")]
    public interface IPropertyObject : IDBusObject
    {
        Task<MyProperties> GetAllAsync();
    }

    public class PropertyObject : IPropertyObject
    {
        public static readonly ObjectPath Path = new ObjectPath("/tmds/dbus/tests/propertyobject");

        public ObjectPath ObjectPath
        {
            get
            {
                return Path;
            }
        }

        public Task<MyProperties> GetAllAsync()
        {
            return Task.FromResult(new MyProperties { Age = 10 });
        }
    }
```

**Comment by kptnk** [comment]
Allright, using a class with the `Dictionary` attribute worked - but using an actual `Dictionary<string, object>` or `IDictionary<string, object>` does not work (anymore?). So the `PropertyObject` from the tests is a little bit misleading.

Thanks for your help.
