### ISSUE TITLE
Cannot get any device connected/disconnected notice

### ISSUE THREAD

**Issue by ptapadiya** [tmds/Tmds.DBus#94]
I am running a BlueZ BLE gatt server and need to know when a client connects.

I have a simple program to monitor BlueZ device connections. Here is the relevant code:

```
           using(var connection = new Connection(Address.System)) {
                connection.StateChanged += (s, e) => OnStateChanged(e);
                await connection.ConnectAsync();
                var dev = connection.CreateProxy<bluez.DBus.IDevice1>("org.bluez", "/org/bluez/hci0");
                await dev.WatchPropertiesAsync(p => {
                    Console.WriteLine(p.ToString());
                });
                var objManager = connection.CreateProxy<bluez.DBus.IObjectManager>("org.bluez", "/org/bluez/hci0");
                await objManager.WatchInterfacesAddedAsync(obj =>
                {
                    Console.WriteLine("Connected");
                });
                ...

    [DBusInterface("org.bluez.Device1")]
    interface IDevice1 : IDBusObject
    {
        ...
        Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
    }

    [DBusInterface("org.freedesktop.DBus.ObjectManager")]
    interface IObjectManager : IDBusObject
    {
        Task<IDisposable> WatchInterfacesAddedAsync(Action<(ObjectPath @object, IDictionary<string, IDictionary<string, object>> interfaces)> handler, Action<Exception> onError = null);
        ...
    }


```
The problem is that I never get any events at all when a client connects or disconnects. However, if I run dbus-monitor, I can see InterfacesAdded on ObjectManager and Property changes on Device1.

Wondering if there is a bug or if I am just missing something.

**Comment by tmds** [comment]
Make sure you don't dispose your Connection, that would stop signals from getting through.

I'm not familiar with bluez. There are a few people using this library with it, maybe you can find some example code that helps you figure out what the issue is.

**Comment by Lucia-Bader** [comment]
> I am running a BlueZ BLE gatt server and need to know when a client connects.
> 
> I have a simple program to monitor BlueZ device connections. Here is the relevant code:
> 
> ```
>            using(var connection = new Connection(Address.System)) {
>                 connection.StateChanged += (s, e) => OnStateChanged(e);
>                 await connection.ConnectAsync();
>                 var dev = connection.CreateProxy<bluez.DBus.IDevice1>("org.bluez", "/org/bluez/hci0");
>                 await dev.WatchPropertiesAsync(p => {
>                     Console.WriteLine(p.ToString());
>                 });
>                 var objManager = connection.CreateProxy<bluez.DBus.IObjectManager>("org.bluez", "/org/bluez/hci0");
>                 await objManager.WatchInterfacesAddedAsync(obj =>
>                 {
>                     Console.WriteLine("Connected");
>                 });
>                 ...
> 
>     [DBusInterface("org.bluez.Device1")]
>     interface IDevice1 : IDBusObject
>     {
>         ...
>         Task<IDisposable> WatchPropertiesAsync(Action<PropertyChanges> handler);
>     }
> 
>     [DBusInterface("org.freedesktop.DBus.ObjectManager")]
>     interface IObjectManager : IDBusObject
>     {
>         Task<IDisposable> WatchInterfacesAddedAsync(Action<(ObjectPath @object, IDictionary<string, IDictionary<string, object>> interfaces)> handler, Action<Exception> onError = null);
>         ...
>     }
> ```
> 
> The problem is that I never get any events at all when a client connects or disconnects. However, if I run dbus-monitor, I can see InterfacesAdded on ObjectManager and Property changes on Device1.
> 
> Wondering if there is a bug or if I am just missing something.

@ptapadiya Could you figure out the problem? If yes what was the problem?

**Comment by ptapadiya** [comment]
No. I couldn't. The project I was working on was experimental and was
scrapped.

Pradeep

**Comment by Lucia-Bader** [comment]
Thanks for your reply!
