### ISSUE TITLE
Allow direct access to underlying variant type

### ISSUE THREAD

**Issue by kekekeks** [tmds/Tmds.DBus#95]
Complex types like `IBusText` and `IBusAttrList` require custom on-the-wire serialization.
Qt allows to do that by exposing `QDBusArgument` class with arbitrary structure.

**Comment by kekekeks** [comment]
GTK DBus implementation directly supports `GVariant` and allows building variant data with `GVariantBuilder`

**Comment by tmds** [comment]
I don't have plans to work on this, so I'm going to close it.

If others have an interested in this, you can add a message to this ticket or a thumbs up to the top comment.
