### ISSUE TITLE
Code generator unhandled exception

### ISSUE THREAD

**Issue by sherif-elmetainy** [tmds/Tmds.DBus#98]
I am trying to generate code for org.bluez service on a raspberry pi. I use the following command:
```bash
dotnet dbus codegen --bus system --service org.bluez
```
It works fine, however some experimental interface which I need are not generated. So I modified the arguments to bluetoothd and added -E so that experimental interface are generated. Now when I ran the same command above again, I get the following exception:

> Unhandled exception. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
>  ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Tmds.DBus.Tool.Generator.ParseType(String dbusType, Int32& index, List`1 elementNames) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 295
>    at Tmds.DBus.Tool.Generator.ParseType(String dbusType, List`1 elementNames) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 284
>    at Tmds.DBus.Tool.Generator.InArgToParameter(XElement argXml, Int32 idx) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 364
>    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
>    at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
>    at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
>    at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsParameterList(IEnumerable`1 parameters)
>    at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.MethodDeclaration(String name, IEnumerable`1 parameters, IEnumerable`1 typeParameters, SyntaxNode returnType, Accessibility accessibility, DeclarationModifiers modifiers, IEnumerable`1 statements)
>    at Tmds.DBus.Tool.Generator.MethodDeclaration(XElement methodXml) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 266
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
>    at Microsoft.CodeAnalysis.SyntaxList`1.CreateNode(IEnumerable`1 nodes)
>    at Microsoft.CodeAnalysis.SyntaxList`1..ctor(IEnumerable`1 nodes)
>    at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.List[TNode](IEnumerable`1 nodes)
>    at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsInterfaceMembers(IEnumerable`1 members)
>    at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InterfaceDeclaration(String name, IEnumerable`1 typeParameters, Accessibility accessibility, IEnumerable`1 interfaceTypes, IEnumerable`1 members)
>    at Tmds.DBus.Tool.Generator.InterfaceDeclaration(String name, XElement interfaceXml) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 114
>    at Tmds.DBus.Tool.Generator.DBusInterfaceDeclaration(String name, XElement interfaceXml)+MoveNext() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 88
>    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
>    at Tmds.DBus.Tool.Generator.Generate(IEnumerable`1 interfaceDescriptions) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Generator.cs:line 73
>    at Tmds.DBus.Tool.CodeGenCommand.GenerateCodeAsync(CodeGenArguments codeGenArguments) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 186
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at Tmds.DBus.Tool.CodeGenCommand.Execute() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/CodeGenCommand.cs:line 87
>    at Tmds.DBus.Tool.Command.<.ctor>b__4_1() in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Command.cs:line 17
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Tmds.DBus.Tool.Program.Main(String[] args) in /home/tmds/repos/Tmds.DBus/src/Tmds.DBus.Tool/Program.cs:line 15

So apparently the experimental interfaces are exposing a type the tool doesn't know how to parse. Is there a way I can display the metadata so that I can find which type is failing to parse?

P.S. Thanks for creating this tool.

**Comment by sherif-elmetainy** [comment]
Update: 

I debugged the tool and the XML that failed to parse was:
```xml
<interface name="org.bluez.SimAccessTest1">
  <method name="OngoingCall">
    <arg name="ongoing" type="b" direction="in" />
  </method>
  <method name="MaxMessageSize">
    <arg name="size" type="u" direction="in" />
  </method>
  <method name="DisconnectImmediate"></method>
  <method name="CardStatus">
    <arg name="status" type="" direction="in" />
  </method>
</interface>
```
You can see that status `<arg name="status" type="" direction="in" />` has an empty type attribute. Since length is zero, an IndexOutRangeException is thrown when attempting to parse the type. I don't whose bug is this (bug in bluez service or bug in the tool not handling empty types).

**Comment by tmds** [comment]
> I don't whose bug is this (bug in bluez service or bug in the tool not handling empty types).

Seems like a bluez bug. Have you reported it?

**Comment by qmfrederik** [comment]
https://marc.info/?l=linux-bluetooth&m=162523385506734&w=2 should fix this on the BlueZ side (not sure this is a priority for them, though). It would be nice for the tool not to crash on invalid input 😄 .
